function breadcrumb_string = GitMatlabBreadCrumbString(info)

% Write a file with the commit hash into the folder, for good measure
breadcrumb_string = sprintf('Matlab version:\n%s\nSource repo:\n%s\nCommit hash:\n%s\nRemote info:\n%s\nGit status:\n%s\n', ...
  info.matlab_ver_string, ...
  info.source_repo_folder_path, ...
  info.commit_hash, ...
  info.git_remote_report, ...
  info.git_status) ;