function breadcrumb_string = GitMatlabBreadCrumbString(info)
% Get a single string summarizing the version info in info, suitable for
% printing.  This is a pure function.

breadcrumb_string = ...
  sprintf('Matlab version:\n%s\nSource repo:\n%s\nCommit hash:\n%s\nRemote info:\n%s\nGit status:\n%s\n', ...
          info.matlab_ver_string, ...
          info.source_repo_folder_path, ...
          info.commit_hash, ...
          info.git_remote_report, ...
          info.git_status) ;
