function isvalid = isPrevAxesModeInfoValid(target)
  isvalid = ~isempty(target) && isstruct(target) && isfield(target,'frm') && ...
            ~isempty(target.frm) && target.frm > 0 && ...
            isfield(target,'iMov') && ~isempty(target.iMov);
end
