function isvalid = isPrevAxesModeInfoValid(paModeInfo)      
  isvalid = ~isempty(paModeInfo) && isstruct(paModeInfo) && isfield(paModeInfo,'frm') && ...
            ~isempty(paModeInfo.frm) && paModeInfo.frm > 0 && ...
            isfield(paModeInfo,'iMov') && ~isempty(paModeInfo.iMov);      
end
