classdef HistEq
  
  methods (Static)
    
    function [imovsel,cntsel] = selMovCentralImHist(cntmat,bins,varargin)
      % Select a movie with a central/median imhist
      %
      % cntmat: [nbin x nmovset x nvw]. cntmat(:,imov,ivw) contains the
      %   imhist (with binning given by bins) for the given movie/view. 
      %   Typically this will be generated by sampling the given movie.
      %   cntmat need not be normalized ie sum(cntmat(:,imov,ivw)) does not
      %   need to be constant over imov,ivw.
      % bins: [nbin x 1] monotonic imhist bin vector
      %
      % imovsel: [nvw] selected movie indices that have central/typical
      %   imhists
      % cntsel: [nbin x nvw] imhist counts (raw, not normalized) for
      %   selected movie in each view
      
      debugviz = myparse(varargin,...
        'debugviz',false... % set to true for a debug/viz plot
        );
      
      if isempty(cntmat)
        error('Input count matrix cannot be empty.');
      end
      
      [nbin,nmov,nvw] = size(cntmat);
      szassert(bins,[nbin 1]);
      
      cntmatsum = sum(cntmat,1);
      cntmatnorm = cntmat./repmat(cntmatsum,[nbin 1 1]); % don't assume autobsx 16b
      cntmatnormcum = cumsum(cntmatnorm,1); % [nbin x nmov x nvw]. columns are imhist CDFs with final el==1
      
      cntmatnormcummdn = median(cntmatnormcum,2); % [nbin x 1 x nvw]
      % metric is sum(abs(d_cumulativeimhist))
      cntmatdst = sum(abs(cntmatnormcum-repmat(cntmatnormcummdn,1,nmov,nvw)),1); % [1 x nmov x nvw]
      cntmatdst = reshape(cntmatdst,nmov,nvw)/nbin; % [nmov x nvw]. average value of d_normalizedCDF over bins
      [cntmatdstsorted,imovssorted] = sort(cntmatdst,1);
      
      imovsel = imovssorted(1,:);
      cntsel = nan(nbin,nvw);
      for ivw=1:nvw
        cntsel(:,ivw) = cntmat(:,imovsel(ivw),ivw);
      end

      if debugviz
        figure;
        axs = mycreatesubplots(nvw,2,.1); % col1: imhist. col2: cdf
        for ivw=1:nvw
          ax = axs(ivw,2);
          axes(ax);
          plot(bins,cntmatnormcum(:,:,ivw));
          hold on
          hplot(1) = plot(bins,cntmatnormcummdn(:,:,ivw),'r-','linewidth',2);
          hplot(2) = plot(bins,cntmatnormcum(:,imovsel(ivw),ivw),'b-','linewidth',2);
          grid on;
          if ivw==1
            legend(hplot,'median','selected');
          end
          
          fprintf('best imhist distances:\n');
          tmp = cntmatdstsorted(:,ivw);
          tmp = tmp(1:min(end,10));
          disp(tmp);
          
          ax = axs(ivw,1);
          axes(ax);
          plot(bins,log10(cntmatnorm(:,:,ivw)));
          hold on;
          plot(bins,log10(cntmatnorm(:,imovsel(ivw),ivw)),'b-','linewidth',2);
          tstr = sprintf('imhist, %d movs, view%d',nmov,ivw);
          title(tstr,'fontweight','bold');
          grid on;
        end
      end
    end
    
  end

  
end