classdef TrackModeEnum < TrackMode
  % Some "canned" TrackModes for track pulldown menu.
  
  enumeration
    CurrMovTgtEveryFrame (MovieIndexSet.CurrentMov,FrameSet.AllFrm,...
      FrameDecimation.EveryFrame,TargetSet.CurrTgt)
    CurrMovTgtEveryLblFrame (MovieIndexSet.CurrentMov,FrameSet.LabeledFrm,...
      FrameDecimation.EveryFrame,TargetSet.CurrTgt)
    CurrMovTgtEveryNFramesSmall (MovieIndexSet.CurrentMov,FrameSet.AllFrm,...
      FrameDecimation.EveryNFrameSmall,TargetSet.CurrTgt)
    CurrMovTgtEveryNFramesLarge (MovieIndexSet.CurrentMov,FrameSet.AllFrm,...
      FrameDecimation.EveryNFrameLarge,TargetSet.CurrTgt)
    CurrMovTgtSelectedFrames (MovieIndexSet.CurrentMov,FrameSet.SelFrm,...
      FrameDecimation.EveryFrame,TargetSet.CurrTgt)
    CurrMovTgtSelectedFramesEveryNFramesSmall (MovieIndexSet.CurrentMov,...
      FrameSet.SelFrm,FrameDecimation.EveryNFrameSmall,TargetSet.CurrTgt)
    CurrMovTgtSelectedFramesEveryNFramesLarge (MovieIndexSet.CurrentMov,...
      FrameSet.SelFrm,FrameDecimation.EveryNFrameLarge,TargetSet.CurrTgt)
    CurrMovTgtNearCurrFrame (MovieIndexSet.CurrentMov,...
      FrameSet.WithinCurrFrm,FrameDecimation.EveryFrame,TargetSet.CurrTgt)
    CurrMovTgtNearCurrFrameEveryNFramesSmall (MovieIndexSet.CurrentMov,...
      FrameSet.WithinCurrFrm,FrameDecimation.EveryNFrameSmall,TargetSet.CurrTgt)
    CurrMovTgtNearCurrFrameEveryNFramesLarge (MovieIndexSet.CurrentMov,...
      FrameSet.WithinCurrFrm,FrameDecimation.EveryNFrameLarge,TargetSet.CurrTgt)
  end
end