classdef TrackModeEnum < TrackMode
  % Some "canned" TrackModes for track pulldown menu.
  
  enumeration
    CurrMovTgtEveryFrame (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.AllFrm,...
      FrameDecimationFixed.EveryFrame,TargetSetVariable.CurrTgt)
    CurrMovTgtEveryLblFrame (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.LabeledFrm,...
      FrameDecimationFixed.EveryFrame,TargetSetVariable.CurrTgt)
    CurrMovTgtEveryNFramesSmall (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.AllFrm,...
      FrameDecimationVariable.EveryNFrameSmall,TargetSetVariable.CurrTgt)
    CurrMovTgtEveryNFramesLarge (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.AllFrm,...
      FrameDecimationVariable.EveryNFrameLarge,TargetSetVariable.CurrTgt)
    CurrMovTgtSelectedFrames (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.SelFrm,...
      FrameDecimationFixed.EveryFrame,TargetSetVariable.CurrTgt)
    CurrMovTgtSelectedFramesEveryNFramesSmall (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.SelFrm,...
      FrameDecimationVariable.EveryNFrameSmall,TargetSetVariable.CurrTgt)
    CurrMovTgtSelectedFramesEveryNFramesLarge (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.SelFrm,...
      FrameDecimationVariable.EveryNFrameLarge,TargetSetVariable.CurrTgt)
    CurrMovTgtNearCurrFrame (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.WithinCurrFrm,...
      FrameDecimationFixed.EveryFrame,TargetSetVariable.CurrTgt)
    CurrMovTgtNearCurrFrameEveryNFramesSmall (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.WithinCurrFrm,...
      FrameDecimationVariable.EveryNFrameSmall,TargetSetVariable.CurrTgt)
    CurrMovTgtNearCurrFrameEveryNFramesLarge (...
      MovieIndexSetVariable.CurrMov,FrameSetVariable.WithinCurrFrm,...
      FrameDecimationVariable.EveryNFrameLarge,TargetSetVariable.CurrTgt)
  end
end