function result = janelia_taylora_aws_backend_params()
  if strcmp(get_user_name(), 'taylora') ,
    jrcAdditionalBsubArgs = '-P scicompsoft' ;
  else
    jrcAdditionalBsubArgs = '' ;
  end
  result = ...
    {'jrcgpuqueue','gpu_a100', ...
     'jrcnslots',4, ...
     'jrcAdditionalBsubArgs',jrcAdditionalBsubArgs, ...
     'awsKeyName', 'alt_taylora-ws4', ...
     'awsPEM', '/home/taylora/.ssh/alt_taylora-ws4.pem', ...
     'awsInstanceID', 'i-0da079e9b4d2d66b9'} ;
end  % function    
