function test_confidence_bouts_from_trk_file()
% Test confidenceBoutsFromTrkFile() with synthetic triangle-wave confidence.

% Define two synthetic tracklets with different confidence ranges.
trackletSpecs(1) = struct( ...
  'frameIndices', 1:6, ...
  'targetIndex', 101, ...
  'period', 8, ...
  'phaseOffset', 0, ...
  'amplitude', 1.0, ...
  'offset', 0.0) ;
trackletSpecs(2) = struct( ...
  'frameIndices', 20:25, ...
  'targetIndex', 202, ...
  'period', 8, ...
  'phaseOffset', 0, ...
  'amplitude', 0.8, ...
  'offset', 0.1) ;

% Verify that the default mock returns different confidences by landmark.
trkFile = TrkFileMock(trackletSpecs, [], false) ;
[~, ~, ~, rawConfidence] = trkFile.getPTrkTgt(1, 'auxflds', {'pTrkConf'}) ;
confidenceFromLandmarkIndex = rawConfidence(:, 1, 1, 1) ;
assertVectorsAlmostEqual(confidenceFromLandmarkIndex, [0; 0.25; 0.5], ...
                         'per-landmark confidence at first frame') ;

% Verify that the lack-thereof mode negates the generated confidence.
trkFileLackThereof = TrkFileMock(trackletSpecs, [], true) ;
[~, ~, ~, rawConfidence] = trkFileLackThereof.getPTrkTgt(1, 'auxflds', {'pTrkConf'}) ;
confidenceFromLandmarkIndex = rawConfidence(:, 1, 1, 1) ;
assertVectorsAlmostEqual(confidenceFromLandmarkIndex, [0; -0.25; -0.5], ...
                         'lack-thereof confidence at first frame') ;

% Check the four quantile-mode cases systematically.
caseInfo = struct( ...
  'label', {'low threshold, normal confidence', ...
            'low threshold, lack-thereof confidence', ...
            'high threshold, normal confidence', ...
            'high threshold, lack-thereof confidence'}, ...
  'trkFile', {trkFile, trkFileLackThereof, trkFile, trkFileLackThereof}, ...
  'quantileThreshold', {0.3, 0.3, 0.7, 0.7}, ...
  'isConfidenceLackThereof', {false, true, false, true}, ...
  'expectedFirstFrameIndex', {[1; 20; 6], [1; 20; 6], [1; 20; 5; 24], [1; 20; 5; 24]}, ...
  'expectedLastFrameIndex', {[2; 20; 6], [2; 20; 6], [3; 22; 6; 25], [3; 22; 6; 25]}, ...
  'expectedExtremalFrameIndex', {[1; 20; 6], [1; 20; 6], [1; 20; 6; 25], [1; 20; 6; 25]}, ...
  'expectedTrackletIndex', {[1; 2; 1], [1; 2; 1], [1; 2; 1; 2], [1; 2; 1; 2]}, ...
  'expectedTargetIndex', {[101; 202; 101], [101; 202; 101], [101; 202; 101; 202], [101; 202; 101; 202]}, ...
  'expectedExtremalConf', {[0; 0.1; 0.25], [0; -0.1; -0.25], [0; 0.1; 0.25; 0.3], [0; -0.1; -0.25; -0.3]}, ...
  'expectedMinConf', {0, -1, 0, -1}, ...
  'expectedMaxConf', {1, 0, 1, 0}) ;
for caseIndex = 1 : numel(caseInfo)
  thisCase = caseInfo(caseIndex) ;
  [firstFrameIndex, lastFrameIndex, extremalFrameIndex, ...
   trackletIndex, targetIndex, extremalConf, minConf, maxConf] = ...
    confidenceBoutsFromTrkFile(thisCase.trkFile, ...
                               thisCase.quantileThreshold, ...
                               thisCase.isConfidenceLackThereof) ;

  assertVectorsEqual(firstFrameIndex, ...
                     thisCase.expectedFirstFrameIndex, ...
                     [thisCase.label ' firstFrameIndex']) ;
  assertVectorsEqual(lastFrameIndex, ...
                     thisCase.expectedLastFrameIndex, ...
                     [thisCase.label ' lastFrameIndex']) ;
  assertVectorsEqual(extremalFrameIndex, ...
                     thisCase.expectedExtremalFrameIndex, ...
                     [thisCase.label ' extremalFrameIndex']) ;
  assertVectorsEqual(trackletIndex, ...
                     thisCase.expectedTrackletIndex, ...
                     [thisCase.label ' trackletIndex']) ;
  assertVectorsEqual(targetIndex, ...
                     thisCase.expectedTargetIndex, ...
                     [thisCase.label ' targetIndex']) ;
  assertVectorsAlmostEqual(extremalConf, ...
                           thisCase.expectedExtremalConf, ...
                           [thisCase.label ' extremalConf']) ;
  assertScalarsAlmostEqual(minConf, ...
                           thisCase.expectedMinConf, ...
                           [thisCase.label ' minConf']) ;
  assertScalarsAlmostEqual(maxConf, ...
                           thisCase.expectedMaxConf, ...
                           [thisCase.label ' maxConf']) ;
end

% Verify invariance across the normal and negated-confidence versions.
casePairInfo = struct( ...
  'label', {'low threshold invariance', 'high threshold invariance'}, ...
  'normalCaseIndex', {1, 3}, ...
  'lackThereofCaseIndex', {2, 4}) ;
for casePairIndex = 1 : numel(casePairInfo)
  thisPair = casePairInfo(casePairIndex) ;
  normalCase = caseInfo(thisPair.normalCaseIndex) ;
  lackThereofCase = caseInfo(thisPair.lackThereofCaseIndex) ;
  assertVectorsEqual(lackThereofCase.expectedFirstFrameIndex, ...
                     normalCase.expectedFirstFrameIndex, ...
                     [thisPair.label ' firstFrameIndex']) ;
  assertVectorsEqual(lackThereofCase.expectedLastFrameIndex, ...
                     normalCase.expectedLastFrameIndex, ...
                     [thisPair.label ' lastFrameIndex']) ;
  assertVectorsEqual(lackThereofCase.expectedExtremalFrameIndex, ...
                     normalCase.expectedExtremalFrameIndex, ...
                     [thisPair.label ' extremalFrameIndex']) ;
end
end  % function



function assertVectorsEqual(actual, expected, label)
if ~isequal(actual, expected)
  error('test_confidence_bouts_from_trk_file:Mismatch', ...
        '%s mismatch. Expected %s, got %s.', ...
        label, mat2str(expected), mat2str(actual)) ;
end
end  % function



function assertVectorsAlmostEqual(actual, expected, label)
tolerance = 1e-12 ;
if ~isequal(size(actual), size(expected)) || any(abs(actual - expected) > tolerance)
  error('test_confidence_bouts_from_trk_file:Mismatch', ...
        '%s mismatch. Expected %s, got %s.', ...
        label, mat2str(expected), mat2str(actual)) ;
end
end  % function



function assertScalarsAlmostEqual(actual, expected, label)
tolerance = 1e-12 ;
if abs(actual - expected) > tolerance
  error('test_confidence_bouts_from_trk_file:Mismatch', ...
        '%s mismatch. Expected %g, got %g.', ...
        label, expected, actual) ;
end
end  % function
