function test_parameter_visualization_classes()
  % Tests that the ParameterVisualization* classes exist on the path and
  % parse cleanly.

  classNames = { ...
    'ParameterVisualizationCPR', ...
    'ParameterVisualizationCPRInit', ...
    'ParameterVisualizationFeature', ...
    'ParameterVisualizationMemory', ...
    'ParameterVisualizationTgtCropRadius', ...
    'ParameterVisualizationTgtCropRadiusID', ...
  } ;
  for i = 1 : numel(classNames)
    name = classNames{i} ;
    if exist(name, 'class') ~= 8
      error('Class %s does not exist on the path', name) ;
    end
  end
end  % function
