function test_interest_bouts_from_per_tracklet_data()
% Test interestBoutsFromPerTrackletData() with hand-crafted per-tracklet
% interest data.

% Three synthetic tracklets, each described by parallel
% (frameIndex, interest) column vectors plus a scalar tracklet index and
% target index.
frameIndexPerTracklet = {[1; 2; 3; 4; 5; 6], ...
                         [20; 21; 22; 23; 24; 25], ...
                         [30; 31; 32; 33; 34; 35]} ;
interestPerTracklet = {[5; 3; 1; 2; 7; 8], ...
                       [1; 4; 6; 5; 2; 1], ...
                       [0; 1; 9; 10; 8; 1]} ;
trackletIndexPerTracklet = {1, 2, 3} ;
targetIndexPerTracklet = {101, 202, 303} ;

% Check two quantile cases: a "low" one that keeps several bouts, and a
% "high" one that keeps only the very top.
caseInfo = struct( ...
  'label', {'low threshold', 'high threshold'}, ...
  'quantileThreshold', {0.7, 0.9}, ...
  'expectedFirstFrameIndex', {[32; 5], ...
                              [32]}, ...
  'expectedLastFrameIndex', {[34; 6], ...
                             [33]}, ...
  'expectedMaxInterestFrameIndex', {[33; 6], ...
                                    [33]}, ...
  'expectedTrackletIndex', {[3; 1], ...
                            [3]}, ...
  'expectedTargetIndex', {[303; 101], ...
                          [303]}, ...
  'expectedMaxInterest', {[10; 8], ...
                          [10]}, ...
  'expectedAbsoluteThreshold', {6.1, 8.7}) ;
% First pass: compute results for each case (so plotting still happens on
% failure).
resultFromCaseIndex = cell(numel(caseInfo), 1) ;
for caseIndex = 1 : numel(caseInfo)
  thisCase = caseInfo(caseIndex) ;
  [firstFrameIndex, lastFrameIndex, maxInterestFrameIndex, ...
   trackletIndex, targetIndex, maxInterest, absoluteThreshold] = ...
    interestBoutsFromPerTrackletData(frameIndexPerTracklet, ...
                                     trackletIndexPerTracklet, ...
                                     targetIndexPerTracklet, ...
                                     interestPerTracklet, ...
                                     thisCase.quantileThreshold) ;
  resultFromCaseIndex{caseIndex} = struct( ...
    'firstFrameIndex', firstFrameIndex, ...
    'lastFrameIndex', lastFrameIndex, ...
    'maxInterestFrameIndex', maxInterestFrameIndex, ...
    'trackletIndex', trackletIndex, ...
    'targetIndex', targetIndex, ...
    'maxInterest', maxInterest, ...
    'absoluteThreshold', absoluteThreshold) ;
end

% Plot each case for visual inspection.
f = plotAllCases(caseInfo, ...
                 frameIndexPerTracklet, ...
                 interestPerTracklet, ...
                 trackletIndexPerTracklet, ...
                 resultFromCaseIndex) ;
cleaner = onCleanup(@()(delete(f))) ;  %#ok<NASGU>
pause(5) ;  % so we can see the fig, if briefly

% Second pass: check each case's results against expectations.
for caseIndex = 1 : numel(caseInfo)
  thisCase = caseInfo(caseIndex) ;
  thisResult = resultFromCaseIndex{caseIndex} ;
  assertVectorsEqual(thisResult.firstFrameIndex, ...
                     thisCase.expectedFirstFrameIndex, ...
                     [thisCase.label ' firstFrameIndex']) ;
  assertVectorsEqual(thisResult.lastFrameIndex, ...
                     thisCase.expectedLastFrameIndex, ...
                     [thisCase.label ' lastFrameIndex']) ;
  assertVectorsEqual(thisResult.maxInterestFrameIndex, ...
                     thisCase.expectedMaxInterestFrameIndex, ...
                     [thisCase.label ' maxInterestFrameIndex']) ;
  assertVectorsEqual(thisResult.trackletIndex, ...
                     thisCase.expectedTrackletIndex, ...
                     [thisCase.label ' trackletIndex']) ;
  assertVectorsEqual(thisResult.targetIndex, ...
                     thisCase.expectedTargetIndex, ...
                     [thisCase.label ' targetIndex']) ;
  assertVectorsAlmostEqual(thisResult.maxInterest, ...
                           thisCase.expectedMaxInterest, ...
                           [thisCase.label ' maxInterest']) ;
  assertScalarsAlmostEqual(thisResult.absoluteThreshold, ...
                           thisCase.expectedAbsoluteThreshold, ...
                           [thisCase.label ' absoluteThreshold']) ;
end

% Verify the empty-data early return still assigns the absolute threshold.
[firstFrameIndex, lastFrameIndex, maxInterestFrameIndex, ...
 trackletIndex, targetIndex, maxInterest, absoluteThreshold] = ...
  interestBoutsFromPerTrackletData(cell(0, 1), ...
                                   cell(0, 1), ...
                                   cell(0, 1), ...
                                   cell(0, 1), ...
                                   0.5) ;
assertVectorsEqual(firstFrameIndex, zeros(0, 1), 'empty firstFrameIndex') ;
assertVectorsEqual(lastFrameIndex, zeros(0, 1), 'empty lastFrameIndex') ;
assertVectorsEqual(maxInterestFrameIndex, zeros(0, 1), 'empty maxInterestFrameIndex') ;
assertVectorsEqual(trackletIndex, zeros(0, 1), 'empty trackletIndex') ;
assertVectorsEqual(targetIndex, zeros(0, 1), 'empty targetIndex') ;
assertVectorsEqual(maxInterest, zeros(0, 1), 'empty maxInterest') ;
assert(isnan(absoluteThreshold), 'Expected empty absoluteThreshold to be NaN') ;
end  % function



function assertVectorsEqual(actual, expected, label)
if ~isequal(actual, expected)
  error('test_interest_bouts_from_per_tracklet_data:Mismatch', ...
        '%s mismatch. Expected %s, got %s.', ...
        label, mat2str(expected), mat2str(actual)) ;
end
end  % function



function assertVectorsAlmostEqual(actual, expected, label)
tolerance = 1e-12 ;
if ~isequal(size(actual), size(expected)) || any(abs(actual - expected) > tolerance)
  error('test_interest_bouts_from_per_tracklet_data:Mismatch', ...
        '%s mismatch. Expected %s, got %s.', ...
        label, mat2str(expected), mat2str(actual)) ;
end
end  % function



function assertScalarsAlmostEqual(actual, expected, label)
tolerance = 1e-12 ;
if abs(actual - expected) > tolerance
  error('test_interest_bouts_from_per_tracklet_data:Mismatch', ...
        '%s mismatch. Expected %g, got %g.', ...
        label, expected, actual) ;
end
end  % function



function f = plotAllCases(caseInfo, ...
                          frameIndexPerTracklet, ...
                          interestPerTracklet, ...
                          trackletIndexPerTracklet, ...
                          resultFromCaseIndex)
% Plot each case in its own subplot for visual inspection.
f = figure('Name', 'test_interest_bouts_from_per_tracklet_data', ...
           'NumberTitle', 'off', ...
           'Color', [1 1 1]) ;
defaultPosition = get(f, 'Position') ;
SetFigureSize(f, 2 * defaultPosition(3), defaultPosition(4)) ;
caseCount = numel(caseInfo) ;
for caseIndex = 1 : caseCount
  subplot(1, caseCount, caseIndex) ;
  plotSingleCase(caseInfo(caseIndex), ...
                 frameIndexPerTracklet, ...
                 interestPerTracklet, ...
                 trackletIndexPerTracklet, ...
                 resultFromCaseIndex{caseIndex}) ;
end
end  % function



function plotSingleCase(thisCase, ...
                        frameIndexPerTracklet, ...
                        interestPerTracklet, ...
                        trackletIndexPerTracklet, ...
                        thisResult)
% Plot one case's per-frame interest values, threshold, and extracted bouts.
trackletCount = numel(frameIndexPerTracklet) ;
colorFromTrackletIndex = lines(trackletCount) ;
hold('on') ;

for trackletIndexLocalIndex = 1 : trackletCount
  trackletIndex = trackletIndexPerTracklet{trackletIndexLocalIndex} ;
  frameIndices = frameIndexPerTracklet{trackletIndexLocalIndex} ;
  interestValues = interestPerTracklet{trackletIndexLocalIndex} ;
  thisColor = colorFromTrackletIndex(trackletIndexLocalIndex, :) ;
  plot(frameIndices, ...
       interestValues, ...
       '-o', ...
       'Color', thisColor, ...
       'MarkerFaceColor', thisColor, ...
       'MarkerSize', 4, ...
       'DisplayName', sprintf('tracklet %d', trackletIndex)) ;
  % Highlight in-bout frames with a larger marker.
  isInBoutFromLocalFrameIndex = false(size(frameIndices)) ;
  for boutIndex = 1 : numel(thisResult.firstFrameIndex)
    if thisResult.trackletIndex(boutIndex) ~= trackletIndex
      continue
    end
    isThisBoutFromLocalFrameIndex = ...
      (frameIndices >= thisResult.firstFrameIndex(boutIndex)) & ...
      (frameIndices <= thisResult.lastFrameIndex(boutIndex)) ;
    isInBoutFromLocalFrameIndex = isInBoutFromLocalFrameIndex | isThisBoutFromLocalFrameIndex ;
  end
  if any(isInBoutFromLocalFrameIndex)
    plot(frameIndices(isInBoutFromLocalFrameIndex), ...
         interestValues(isInBoutFromLocalFrameIndex), ...
         'o', ...
         'Color', thisColor, ...
         'MarkerFaceColor', thisColor, ...
         'MarkerSize', 7, ...
         'HandleVisibility', 'off') ;
  end
end

% Plot horizontal threshold line.
yline(thisResult.absoluteThreshold, ...
      '--k', ...
      sprintf('threshold = %.3f', thisResult.absoluteThreshold), ...
      'LabelHorizontalAlignment', 'left', ...
      'HandleVisibility', 'off') ;

% Mark each bout's max-interest frame with a star.
boutCount = numel(thisResult.firstFrameIndex) ;
for boutIndex = 1 : boutCount
  thisTrackletIndex = thisResult.trackletIndex(boutIndex) ;
  trackletLocalIndex = find(cellfun(@(t)(isequal(t, thisTrackletIndex)), ...
                                    trackletIndexPerTracklet), 1) ;
  thisColor = colorFromTrackletIndex(trackletLocalIndex, :) ;
  maxFrame = thisResult.maxInterestFrameIndex(boutIndex) ;
  maxInterest = thisResult.maxInterest(boutIndex) ;
  plot(maxFrame, ...
       maxInterest, ...
       'p', ...
       'MarkerSize', 12, ...
       'MarkerFaceColor', thisColor, ...
       'MarkerEdgeColor', 'k', ...
       'HandleVisibility', 'off') ;
end

xlabel('frame') ;
ylabel('interest') ;
title(thisCase.label, 'Interpreter', 'none') ;
grid('on') ;
hold('off') ;
end  % function
