function test_confidence_bouts_from_trk_file()
% Test confidenceBoutsFromTrkFile() with synthetic triangle-wave confidence.

% Define three synthetic tracklets with different confidence ranges.  The
% third tracklet's phaseOffset is chosen so its low-confidence region is
% strictly interior to its frame range (does not touch either end), to
% exercise interior-bout handling.
trackletSpecs(1) = struct( ...
  'frameIndices', 1:6, ...
  'targetIndex', 101, ...
  'period', 8, ...
  'phaseOffset', 0, ...
  'amplitude', 1.0, ...
  'offset', 0.0) ;
trackletSpecs(2) = struct( ...
  'frameIndices', 20:25, ...
  'targetIndex', 202, ...
  'period', 8, ...
  'phaseOffset', 0, ...
  'amplitude', 0.8, ...
  'offset', 0.1) ;
trackletSpecs(3) = struct( ...
  'frameIndices', 30:37, ...
  'targetIndex', 303, ...
  'period', 8, ...
  'phaseOffset', 3, ...
  'amplitude', 1.0, ...
  'offset', 0.0) ;

% Verify that the mock returns different confidences by landmark.
trkFile = TrkFileMock(trackletSpecs) ;
[~, ~, ~, rawConfidence] = trkFile.getPTrkTgt(1, 'auxflds', {'pTrkConf'}) ;
confidenceFromLandmarkIndex = rawConfidence(:, 1, 1, 1) ;
assertVectorsAlmostEqual(confidenceFromLandmarkIndex, [0; 0.25; 0.5], ...
                         'per-landmark confidence at first frame') ;

% Check both quantile-threshold cases.
caseInfo = struct( ...
  'label', {'low threshold', 'high threshold'}, ...
  'trkFile', {trkFile, trkFile}, ...
  'quantileThreshold', {0.7, 0.3}, ...
  'expectedFirstFrameIndex', {[1; 32; 20; 6], ...
                              [1; 31; 20; 5; 24]}, ...
  'expectedLastFrameIndex', {[2; 36; 20; 6], ...
                             [3; 37; 22; 6; 25]}, ...
  'expectedMinConfFrameIndex', {[1; 33; 20; 6], ...
                                 [1; 33; 20; 6; 25]}, ...
  'expectedTrackletIndex', {[1; 3; 2; 1], ...
                            [1; 3; 2; 1; 2]}, ...
  'expectedTargetIndex', {[101; 303; 202; 101], ...
                          [101; 303; 202; 101; 202]}, ...
  'expectedBoutMinConf', {[0; 0; 0.1; 0.25], ...
                           [0; 0; 0.1; 0.25; 0.3]}, ...
  'expectedAbsoluteThreshold', {0.25, 0.5}) ;
% First pass: compute results for each case (so plotting still happens on
% failure).
resultFromCaseIndex = cell(numel(caseInfo), 1) ;
for caseIndex = 1 : numel(caseInfo)
  thisCase = caseInfo(caseIndex) ;
  [firstFrameIndex, lastFrameIndex, minConfFrameIndex, ...
   trackletIndex, targetIndex, boutMinConf, absoluteThreshold] = ...
    confidenceBoutsFromTrkFile(thisCase.trkFile, ...
                               thisCase.quantileThreshold) ;
  resultFromCaseIndex{caseIndex} = struct( ...
    'firstFrameIndex', firstFrameIndex, ...
    'lastFrameIndex', lastFrameIndex, ...
    'minConfFrameIndex', minConfFrameIndex, ...
    'trackletIndex', trackletIndex, ...
    'targetIndex', targetIndex, ...
    'boutMinConf', boutMinConf, ...
    'absoluteThreshold', absoluteThreshold) ;
end

% Plot each case for visual inspection.
f = plotAllCases(caseInfo, resultFromCaseIndex) ;
cleaner = onCleanup(@()(delete(f))) ;

% Second pass: check each case's results against expectations.
for caseIndex = 1 : numel(caseInfo)
  thisCase = caseInfo(caseIndex) ;
  thisResult = resultFromCaseIndex{caseIndex} ;
  assertVectorsEqual(thisResult.firstFrameIndex, ...
                     thisCase.expectedFirstFrameIndex, ...
                     [thisCase.label ' firstFrameIndex']) ;
  assertVectorsEqual(thisResult.lastFrameIndex, ...
                     thisCase.expectedLastFrameIndex, ...
                     [thisCase.label ' lastFrameIndex']) ;
  assertVectorsEqual(thisResult.minConfFrameIndex, ...
                     thisCase.expectedMinConfFrameIndex, ...
                     [thisCase.label ' minConfFrameIndex']) ;
  assertVectorsEqual(thisResult.trackletIndex, ...
                     thisCase.expectedTrackletIndex, ...
                     [thisCase.label ' trackletIndex']) ;
  assertVectorsEqual(thisResult.targetIndex, ...
                     thisCase.expectedTargetIndex, ...
                     [thisCase.label ' targetIndex']) ;
  assertVectorsAlmostEqual(thisResult.boutMinConf, ...
                           thisCase.expectedBoutMinConf, ...
                           [thisCase.label ' boutMinConf']) ;
  assertScalarsAlmostEqual(thisResult.absoluteThreshold, ...
                           thisCase.expectedAbsoluteThreshold, ...
                           [thisCase.label ' absoluteThreshold']) ;
end

% Verify the empty-data early return still assigns the absolute threshold.
emptyTrackletSpecs = struct('frameIndices', {}, ...
                            'targetIndex', {}, ...
                            'period', {}, ...
                            'phaseOffset', {}, ...
                            'amplitude', {}, ...
                            'offset', {}) ;
emptyTrkFile = TrkFileMock(emptyTrackletSpecs) ;
[firstFrameIndex, lastFrameIndex, minConfFrameIndex, ...
 trackletIndex, targetIndex, boutMinConf, absoluteThreshold] = ...
  confidenceBoutsFromTrkFile(emptyTrkFile, 0.5) ;
assertVectorsEqual(firstFrameIndex, zeros(0, 1), 'empty firstFrameIndex') ;
assertVectorsEqual(lastFrameIndex, zeros(0, 1), 'empty lastFrameIndex') ;
assertVectorsEqual(minConfFrameIndex, zeros(0, 1), 'empty minConfFrameIndex') ;
assertVectorsEqual(trackletIndex, zeros(0, 1), 'empty trackletIndex') ;
assertVectorsEqual(targetIndex, zeros(0, 1), 'empty targetIndex') ;
assertVectorsEqual(boutMinConf, zeros(0, 1), 'empty boutMinConf') ;
assert(isnan(absoluteThreshold), 'Expected empty absoluteThreshold to be NaN') ;
end  % function



function assertVectorsEqual(actual, expected, label)
if ~isequal(actual, expected)
  error('test_confidence_bouts_from_trk_file:Mismatch', ...
        '%s mismatch. Expected %s, got %s.', ...
        label, mat2str(expected), mat2str(actual)) ;
end
end  % function



function assertVectorsAlmostEqual(actual, expected, label)
tolerance = 1e-12 ;
if ~isequal(size(actual), size(expected)) || any(abs(actual - expected) > tolerance)
  error('test_confidence_bouts_from_trk_file:Mismatch', ...
        '%s mismatch. Expected %s, got %s.', ...
        label, mat2str(expected), mat2str(actual)) ;
end
end  % function



function assertScalarsAlmostEqual(actual, expected, label)
tolerance = 1e-12 ;
if abs(actual - expected) > tolerance
  error('test_confidence_bouts_from_trk_file:Mismatch', ...
        '%s mismatch. Expected %g, got %g.', ...
        label, expected, actual) ;
end
end  % function



function f = plotAllCases(caseInfo, resultFromCaseIndex)
% Plot each case in its own subplot for visual inspection.
f = figure('Name', 'test_confidence_bouts_from_trk_file', ...
           'NumberTitle', 'off', ...
           'Color', [1 1 1]) ;
defaultPosition = get(f, 'Position') ;
SetFigureSize(f, 2 * defaultPosition(3), defaultPosition(4)) ;
caseCount = numel(caseInfo) ;
for caseIndex = 1 : caseCount
  subplot(1, caseCount, caseIndex) ;
  plotSingleCase(caseInfo(caseIndex), resultFromCaseIndex{caseIndex}) ;
end
end  % function



function plotSingleCase(thisCase, thisResult)
% Plot one case's per-frame minimum confidence, threshold, and extracted bouts.
trkFile = thisCase.trkFile ;
trackletCount = trkFile.ntracklets ;
colorFromTrackletIndex = lines(trackletCount) ;
hold('on') ;

% Plot per-frame minimum-over-landmarks confidence per tracklet.
for trackletIndex = 1 : trackletCount
  [~, ~, frameIndexFromFrameIndex, rawConfidence] = ...
    trkFile.getPTrkTgt(trackletIndex, 'auxflds', {'pTrkConf'}) ;
  confFromLandmarkAndFrame = ...
    reshape(rawConfidence, size(rawConfidence, 1), size(rawConfidence, 2)) ;
  relevantConfFromFrame = min(confFromLandmarkAndFrame, [], 1) ;
  thisColor = colorFromTrackletIndex(trackletIndex, :) ;
  plot(frameIndexFromFrameIndex, ...
       relevantConfFromFrame, ...
       '-o', ...
       'Color', thisColor, ...
       'MarkerFaceColor', thisColor, ...
       'MarkerSize', 4, ...
       'DisplayName', sprintf('tracklet %d (target %d)', ...
                              trackletIndex, ...
                              trkFile.pTrkiTgt(trackletIndex))) ;
  % Highlight in-bout frames with a larger marker.
  isInBoutFromFrameIndex = false(size(frameIndexFromFrameIndex)) ;
  for boutIndex = 1 : numel(thisResult.firstFrameIndex)
    if thisResult.trackletIndex(boutIndex) ~= trackletIndex
      continue
    end
    isThisBoutFromFrameIndex = ...
      (frameIndexFromFrameIndex >= thisResult.firstFrameIndex(boutIndex)) & ...
      (frameIndexFromFrameIndex <= thisResult.lastFrameIndex(boutIndex)) ;
    isInBoutFromFrameIndex = isInBoutFromFrameIndex | isThisBoutFromFrameIndex ;
  end
  if any(isInBoutFromFrameIndex)
    plot(frameIndexFromFrameIndex(isInBoutFromFrameIndex), ...
         relevantConfFromFrame(isInBoutFromFrameIndex), ...
         'o', ...
         'Color', thisColor, ...
         'MarkerFaceColor', thisColor, ...
         'MarkerSize', 7, ...
         'HandleVisibility', 'off') ;
  end
end

% Plot horizontal threshold line.
yline(thisResult.absoluteThreshold, ...
      '--k', ...
      sprintf('threshold = %.3f', thisResult.absoluteThreshold), ...
      'LabelHorizontalAlignment', 'left', ...
      'HandleVisibility', 'off') ;

% Mark each bout's min-confidence frame with a star.
boutCount = numel(thisResult.firstFrameIndex) ;
for boutIndex = 1 : boutCount
  thisTrackletIndex = thisResult.trackletIndex(boutIndex) ;
  thisColor = colorFromTrackletIndex(thisTrackletIndex, :) ;
  minConfFrame = thisResult.minConfFrameIndex(boutIndex) ;
  boutMinConf = thisResult.boutMinConf(boutIndex) ;
  plot(minConfFrame, ...
       boutMinConf, ...
       'p', ...
       'MarkerSize', 12, ...
       'MarkerFaceColor', thisColor, ...
       'MarkerEdgeColor', 'k', ...
       'HandleVisibility', 'off') ;
end

xlabel('frame') ;
ylabel('per-frame min conf') ;
title(thisCase.label, 'Interpreter', 'none') ;
grid('on') ;
hold('off') ;
end  % function
