function h1 = createProjectSetupFigure()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the MATLAB file at the MATLAB
% prompt. The MATLAB code file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the MATLAB code file/MAT-file format, and should be saved as
% FIG-files.


load('createProjectSetupFigure.mat', 'mat') ;


appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = mat{2};

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units',get(0,'defaultfigureUnits'),...
'Position',[680 889 854 621],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',[0 0.243 0.365],...
'CloseRequestFcn',@(hObject,eventdata)ProjectSetup('figure1_CloseRequestFcn',hObject,eventdata,guidata(hObject)),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'Colormap',get(0,'defaultfigureColormap'),...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar','none',...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','Project Setup',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','figure1',...
'UserData',[],...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text2';

h2 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Project Name',...
'Style','text',...
'Position',[25 559 137 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text2',...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'text3';

h3 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Number of Keypoints',...
'Style','text',...
'Position',[25 512 220 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text3',...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'text4';

h4 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Number of Views',...
'Style','text',...
'Position',[25 450 179 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text4',...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'etProjectName';

h5 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','edit',...
'Position',[186 555 250 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('etProjectName_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'TooltipString',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','etProjectName',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'etNumberOfPoints';

h6 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'String','12',...
'Style','edit',...
'Position',[282 511 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('etNumberOfPoints_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'TooltipString',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','etNumberOfPoints',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'etNumberOfViews';

h7 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'String','1',...
'Style','edit',...
'Position',[282 452 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('etNumberOfViews_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'TooltipString',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','etNumberOfViews',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pbAdvanced';

h8 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String','Advanced >',...
'Position',[250 64 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbAdvanced_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip','Show advanced options',...
'ForegroundColor',[0 1 1],...
'TooltipString','Show advanced options',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pbAdvanced',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pbCreateProject';

h9 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String','Create Project',...
'Position',[44 21 200 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbCreateProject_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'TooltipString',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pbCreateProject',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pbCancel';

h10 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String','Cancel',...
'Position',[249 21 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbCancel_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'TooltipString',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pbCancel',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pnlAdvanced';

h11 = uipanel(...
'Parent',h1,...
'FontUnits','pixels',...
'Units','pixels',...
'ForegroundColor',[0 1 1],...
'BorderType','none',...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'BackgroundColor',[0 0.243 0.365],...
'Tag','pnlAdvanced',...
'Position',[457 20 377 551],...
'Layout',[],...
'FontSize',13.3333333333333,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text8';

h12 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Advanced Properties',...
'Style','text',...
'Position',[458 564 217 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text8',...
'FontSize',20,...
'FontAngle','italic');

appdata = [];
appdata.lastValidTag = 'landmarkRight';

h13 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String',blanks(0),...
'Style','text',...
'Position',[825 594 8 8],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'Visible','off',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','landmarkRight',...
'FontSize',10.6666666666667,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'pbCopySettingsFrom';

h14 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String','Copy Settings...',...
'Position',[45 63 200 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbCopySettingsFrom_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip','Copy settings from an existing project',...
'ForegroundColor',[0 1 1],...
'TooltipString','Copy settings from an existing project',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pbCopySettingsFrom',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'cbHasTrx';

h15 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String',blanks(0),...
'Style','checkbox',...
'Position',[323 237 24 24],...
'BackgroundColor',[0 0.24 0.36],...
'Callback',@(hObject,eventdata)ProjectSetup('cbHasTrx_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'TooltipString',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','cbHasTrx',...
'FontSize',24);

appdata = [];
appdata.lastValidTag = 'text_multitarget';

h16 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Has Body Tracking?',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[25 235 206 24],...
'BackgroundColor',[0 0.243 0.365],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text_multitarget',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',20,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'cbMA';

h17 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'String',blanks(0),...
'Style','checkbox',...
'Position',[324 338 14 22],...
'BackgroundColor',[0 0.24 0.36],...
'Callback',@(hObject,eventdata)ProjectSetup('cbMA_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'TooltipString',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','cbMA',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'text12';

h18 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Multiple Animals?',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[25 336 202 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text12',...
'UserData',[],...
'FontSize',20,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'landmarkMid';

h19 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[446 439 13 14],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible','off',...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','landmarkMid',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text_nkeypoints_description';

h20 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Number of keypoints to label for each animal',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[27 488 400 24],...
'BackgroundColor',[0 0.243 0.365],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text_nkeypoints_description',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',16,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text_nviews_description';

h21 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','APT can do 3D labeling and tracking from multiple calibrated cameras. Enter 1 if animals were imaged from just one camera. Otherwise, enter the number of synced cameras recording the animals. ',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[26 363 400 85],...
'BackgroundColor',[0 0.243 0.365],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text_nviews_description',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',16,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text_multianimal_description';

h22 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Check this box if there are multiple animals visible in any video frames. Otherwise, APT will assume there is just one animal visible per frame.',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[28 265 400 67],...
'BackgroundColor',[0 0.243 0.365],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text_multianimal_description',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',16,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text16';

h23 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','APT can do pose tracking on top of body tracking from an algorithm like FlyTracker or Ctrax. Check this box if you have already tracked the centroids and orientations of your animals and want to base pose tracking on those trajectories. If so, a trajectory file is input with each video.',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[28 110 400 122],...
'BackgroundColor',[0 0.243 0.365],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',[0 1 1],...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text16',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',16,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end
