function h1 = createProjectSetupFigure()
% Create the figure for Project Setup.

h1 = figure(...
'Position',[680 889 854 621],...
'Color',[0 0.243 0.365],...
'CloseRequestFcn',@(hObject,eventdata)ProjectSetup('figure1_CloseRequestFcn',hObject,eventdata,guidata(hObject)),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'IntegerHandle','off',...
'MenuBar','none',...
'ToolBar','none',...
'Name','Project Setup',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'Tag','figure1',...
'UserData',[],...
'ScreenPixelsPerInchMode','manual');

h2 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Project Name',...
'Style','text',...
'Position',[25 559 137 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text2',...
'FontSize',20);

h3 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Number of Keypoints',...
'Style','text',...
'Position',[25 512 220 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text3',...
'FontSize',20);

h4 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Number of Views',...
'Style','text',...
'Position',[25 450 179 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text4',...
'FontSize',20);

h5 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','edit',...
'Position',[186 555 250 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('etProjectName_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'Tag','etProjectName',...
'FontSize',20);

h6 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String','12',...
'Style','edit',...
'Position',[282 511 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('etNumberOfPoints_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'Tag','etNumberOfPoints',...
'FontSize',20);

h7 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String','1',...
'Style','edit',...
'Position',[282 452 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('etNumberOfViews_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'Tag','etNumberOfViews',...
'FontSize',20);

h8 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String','Advanced >',...
'Position',[250 64 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbAdvanced_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip','Show advanced options',...
'ForegroundColor',[0 1 1],...
'TooltipString','Show advanced options',...
'Tag','pbAdvanced',...
'FontSize',20);

h9 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String','Create Project',...
'Position',[44 21 200 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbCreateProject_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'Tag','pbCreateProject',...
'FontSize',20);

h10 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String','Cancel',...
'Position',[249 21 150 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbCancel_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 0.980392156862745 0.819607843137255],...
'Tag','pbCancel',...
'FontSize',20);

h11 = uipanel(...
'Parent',h1,...
'FontUnits','pixels',...
'Units','pixels',...
'ForegroundColor',[0 1 1],...
'BorderType','none',...
'BackgroundColor',[0 0.243 0.365],...
'Tag','pnlAdvanced',...
'Position',[457 20 377 551],...
'Layout',[],...
'FontSize',13.3333333333333);

h12 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Advanced Properties',...
'Style','text',...
'Position',[458 564 217 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text8',...
'FontSize',20,...
'FontAngle','italic');

h13 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String',blanks(0),...
'Style','text',...
'Position',[825 594 8 8],...
'Children',[],...
'Visible','off',...
'Tag','landmarkRight',...
'FontSize',10.6666666666667);

h14 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String','Copy Settings...',...
'Position',[45 63 200 32],...
'BackgroundColor',[0 0 0],...
'Callback',@(hObject,eventdata)ProjectSetup('pbCopySettingsFrom_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip','Copy settings from an existing project',...
'ForegroundColor',[0 1 1],...
'TooltipString','Copy settings from an existing project',...
'Tag','pbCopySettingsFrom',...
'FontSize',20);

h15 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String',blanks(0),...
'Style','checkbox',...
'Position',[323 237 24 24],...
'BackgroundColor',[0 0.24 0.36],...
'Callback',@(hObject,eventdata)ProjectSetup('cbHasTrx_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','cbHasTrx',...
'FontSize',24);

h16 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Has Body Tracking?',...
'Style','text',...
'Position',[25 235 206 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text_multitarget',...
'UserData',[],...
'FontSize',20);

h17 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'String',blanks(0),...
'Style','checkbox',...
'Position',[324 338 14 22],...
'BackgroundColor',[0 0.24 0.36],...
'Callback',@(hObject,eventdata)ProjectSetup('cbMA_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','cbMA',...
'FontSize',20);

h18 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Multiple Animals?',...
'Style','text',...
'Position',[25 336 202 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text12',...
'UserData',[],...
'FontSize',20);

h19 = uicontrol(...
'Parent',h1,...
'String',blanks(0),...
'Style','text',...
'Position',[446 439 13 14],...
'Children',[],...
'Visible','off',...
'Tag','landmarkMid',...
'UserData',[],...
'FontSize',8);

h20 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Number of keypoints to label for each animal',...
'Style','text',...
'Position',[27 488 400 24],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text_nkeypoints_description',...
'UserData',[],...
'FontSize',16);

h21 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','APT can do 3D labeling and tracking from multiple calibrated cameras. Enter 1 if animals were imaged from just one camera. Otherwise, enter the number of synced cameras recording the animals. ',...
'Style','text',...
'Position',[26 363 400 85],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text_nviews_description',...
'UserData',[],...
'FontSize',16);

h22 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','Check this box if there are multiple animals visible in any video frames. Otherwise, APT will assume there is just one animal visible per frame.',...
'Style','text',...
'Position',[28 265 400 67],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text_multianimal_description',...
'UserData',[],...
'FontSize',16);

h23 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'String','APT can do pose tracking on top of body tracking from an algorithm like FlyTracker or Ctrax. Check this box if you have already tracked the centroids and orientations of your animals and want to base pose tracking on those trajectories. If so, a trajectory file is input with each video.',...
'Style','text',...
'Position',[28 110 400 122],...
'BackgroundColor',[0 0.243 0.365],...
'Children',[],...
'ForegroundColor',[0 1 1],...
'Tag','text16',...
'UserData',[],...
'FontSize',16);
