function varargout = LandmarkColors_export(varargin)
% LANDMARKCOLORS_EXPORT MATLAB code for LandmarkColors_export.fig
%      LANDMARKCOLORS_EXPORT, by itself, creates a new LANDMARKCOLORS_EXPORT or raises the existing
%      singleton*.
%
%      H = LANDMARKCOLORS_EXPORT returns the handle to a new LANDMARKCOLORS_EXPORT or the handle to
%      the existing singleton*.
%
%      LANDMARKCOLORS_EXPORT('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in LANDMARKCOLORS_EXPORT.M with the given input arguments.
%
%      LANDMARKCOLORS_EXPORT('Property','Value',...) creates a new LANDMARKCOLORS_EXPORT or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before LandmarkColors_export_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to LandmarkColors_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help LandmarkColors_export

% Last Modified by GUIDE v2.5 27-Jul-2026 13:59:41

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @LandmarkColors_export_OpeningFcn, ...
                   'gui_OutputFcn',  @LandmarkColors_export_OutputFcn, ...
                   'gui_LayoutFcn',  @LandmarkColors_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1}) && exist(varargin{1}),
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


function LandmarkColors_export_OpeningFcn(hObject, eventdata, handles, varargin)
% [tfchanges,savedinfo] = LandmarkColors_export(controller,lObj,cbk)

% cbk sig: cbk(colorSpecs,markerSpecs,skelSpecs)
%   colorSpecs: array of LandmarkColorSpec objs (could be nonscalar)
%   markerSpecs: [3] struct array nested Marker/TextProps etc
%   skelSpecs: [3] struct array

handles.output = hObject;
set(hObject,'MenuBar','None');

hObject.CloseRequestFcn = @figure_landmarkcolors_CloseRequestFcn;

controller = varargin{1};
lObj = varargin{2};
handles.nlandmarks = lObj.nPhysPoints;
handles.applyCbkFcn = varargin{3}; % sig:

mainFigurePosition = controller.mainFigurePixelPosition() ;
centerOnOtherFigureGivenPositionBang(hObject, mainFigurePosition) ;


% Marker State
% This is stored only in the table. Get and Set using Set/GetMarker*.
lsetTypesCell = num2cell(enumeration('LandmarkSetType'));
ppiAll = {lObj.labelPointsPlotInfo; lObj.predPointsPlotInfo};
FLDS = {'MarkerProps' 'TextProps' 'TextOffset'};
sPropsMrkr = cellfun(@(x)structrestrictflds(x,FLDS),ppiAll);
[sPropsMrkr.landmarkSetType] = deal(lsetTypesCell{:});
% Color State
% This state is maintained in handles.colorSpecs. What is shown in the
% Colors pane is per pumShowing.
lsetTypesCellCount = numel(lsetTypesCell) ;
handles.colorSpecs = ...
  cellfun(@(x1,x2,x3)LandmarkColorSpec(x1,x2,x3), ...
          lsetTypesCell, ...
          repmat({lObj.nPhysPoints},lsetTypesCellCount,1), ...
          ppiAll) ;
% Skel State
FLDS = {'SkeletonProps'};
sPropsSkel = cellfun(@(x)structrestrictflds(x,FLDS),ppiAll);
[sPropsSkel.landmarkSetType] = deal(lsetTypesCell{:});

handles.sPropsMrkr0 = sPropsMrkr;
handles.colorSpecs0 = handles.colorSpecs.copy();
handles.sPropsSkel0 = sPropsSkel;

handles = initColorsPane(handles);
updateColorsPane(handles);

MARKERS = 'o+*.xsd^v><ph';
MARKERS = num2cell(MARKERS);
tbl = handles.tblProps;
tbl.ColumnFormat{1} = MARKERS;
strcmp(tbl.ColumnName{6},'Label Font Angle');
tbl.ColumnFormat{6} = {'normal' 'italic'};
ncol = numel(tbl.ColumnFormat);
set(tbl,'Data',cell(3,ncol),'RowName',{'Label' 'Prediction'});

MarkerControlsSet(handles,sPropsMrkr);

handles.sldSkeletonLineWidth.Min = -1; %log scale
handles.sldSkeletonLineWidth.Max = 5;
handles.hSldListener = addlistener(handles.sldSkeletonLineWidth,...
  'ContinuousValueChange',@(s,e)sldSkeletonLineWidth_Callback(s,[],guidata(s)));
SkelControlsSet(handles,sPropsSkel);

set(handles.figure_landmarkcolors,'Name','Landmark Cosmetics');
handles.saved = [];
guidata(hObject, handles);

handles.tblProps.CellEditCallback = @tblCellEditCallback;

% UIWAIT makes LandmarkColors_export wait for user response (see UIRESUME)
uiwait(handles.figure_landmarkcolors);


function tblCellEditCallback(src,evt)
handles = guidata(src);
pbApply_Callback(handles.output,[],handles);


%%%%%%%%%%
% COLORS %
%%%%%%%%%%

function handles = initColorsPane(handles)
pum = handles.pumShowing;
pum.String = { ...
  'Labels'
  'Predictions'
  };
pum.Value = 1;

% Colormap pulldown options
pum = handles.popupmenu_colormap;
cmapnames = LandmarkColorSpec.CMAPNAMES;
ncmapnames = numel(cmapnames);
cmapname2idx = cell2struct(num2cell(1:ncmapnames),cmapnames,2);
set(pum,'String',LandmarkColorSpec.CMAPNAMES,'Value',1,'UserData',cmapname2idx);

handles.colormapim = imagesc(1:handles.nlandmarks,'Parent',handles.axes_colormap);
axis(handles.axes_colormap,'off');

% create buttons
w = 1/handles.nlandmarks;
borderfrac = .05;
for i = 1:handles.nlandmarks,  
  handles.hbuttons(i) = uicontrol('style','pushbutton',...
    'ForegroundColor','k',...
    'BackgroundColor',[0.5 0.5 0.5],...
    'Units','normalized',...
    'Position',[w*borderfrac+w*(i-1),borderfrac,w*(1-2*borderfrac),1-2*borderfrac],...
    'Parent',handles.uipanel_manual,...
    'Callback',@(hObject,eventdata)LandmarkColors('pushbutton_manual_Callback',hObject,eventdata,guidata(hObject),i),...
    'Tag',sprintf('pushbutton_manual_%d',i),...
    'String',num2str(i));
end

function updateColorsPane(handles)
% Update colors pane uicontrols per current colorSpecs

cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);

% mode
btnGrp = handles.radiobutton_manual.Parent;
if cs.tfmanual
  btnGrp.SelectedObject = handles.radiobutton_manual;
else
  btnGrp.SelectedObject = handles.radiobutton_colormap;
end

UpdateColorMode(handles);

if cs.tfmanual
  % manual button colors
  for i = 1:handles.nlandmarks,
    set(handles.hbuttons(i),'BackgroundColor',cs.colors(i,:));
  end
else
  % colormapname
  cmapname = cs.colormapname;
  pumcmap = handles.popupmenu_colormap;
  cmapidx = pumcmap.UserData.(cmapname);
  pumcmap.Value = cmapidx;

  % colormap
  colormap(handles.axes_colormap,cs.colormap);

  % brightness
  set(handles.edit_brightness,'String',num2str(cs.brightness));
  set(handles.slider_brightness,'Value',cs.brightness);
end

function UpdateColorMode(handles)
% enable/disable based on radiobutton setting
v = get(handles.radiobutton_manual,'Value');
hcm = findobj(handles.uipanel_colormap,'-property','Enable');
hm = findobj(handles.uipanel_manual,'-property','Enable');
if v == 1,
  set(hcm,'Enable','off');
  set(hm,'Enable','on');
else
  set(hcm,'Enable','on');
  set(hm,'Enable','off');
end

% function UpdateButtonColors(handles)

function pumShowing_Callback(hObject, eventdata, handles)
updateColorsPane(handles);

function popupmenu_colormap_Callback(hObject, eventdata, handles)
contents = cellstr(get(hObject,'String'));
cmapname = contents{get(hObject,'Value')};

cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);
cs.setColormapName(cmapname);
updateColorsPane(handles);
pbApply_Callback(handles.output,[],handles);

function slider_brightness_Callback(hObject, eventdata, handles)
v = get(hObject,'Value');
cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);
cs.setBrightness(v);
updateColorsPane(handles);
pbApply_Callback(handles.output,[],handles);

function edit_brightness_Callback(hObject, eventdata, handles)
v = str2double(get(hObject,'String'));
cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);

if isnan(v) || v < 0 || v > 1,
  warndlg('Brightness must be a number between 0 and 1','Error setting brightness','modal');
  set(hObject,'String',num2str(cs.brightness));
else
  cs.setBrightness(v);
  %set(handles.slider_brightness,'Value',v);
  updateColorsPane(handles);
  pbApply_Callback(handles.output,[],handles);
end

function radiobutton_colormap_Callback(hObject, eventdata, handles)
cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);
cs.setTFManual(false);
updateColorsPane(handles);

function radiobutton_manual_Callback(hObject, eventdata, handles)
cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);
cs.setManualColorsToColormap();
cs.setTFManual(true);
updateColorsPane(handles);

function pushbutton_manual_Callback(hObject, eventdata, handles, landmarki)
% fprintf('Landmark %d\n',landmarki);
cs = handles.colorSpecs;
iCS = handles.pumShowing.Value;
cs = cs(iCS);
clr = uisetcolor(cs.colors(landmarki,:),sprintf('Landmark %d color',landmarki));
cs.setColorManual(landmarki,clr);
updateColorsPane(handles);
pbApply_Callback(handles.output,[],handles);

function pumShowing_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function slider_brightness_CreateFcn(hObject, eventdata, handles)
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end

function edit_brightness_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function popupmenu_colormap_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


%%%%%%%%%%%
% MARKERS %
%%%%%%%%%%%

function MarkerControlsSet(handles,s)
% Set tblProps per pvStructs
%
% s: as in structure returned by MarkerControlsGet

uitbl = handles.tblProps;
assert(isequal(uitbl.RowName,{'Label' 'Prediction'}'));

FLDS_MARKER = {'Marker' 'MarkerSize' 'LineWidth'};
tMrkr = struct2table([s.MarkerProps]');
assert(isequal(tMrkr.Properties.VariableNames,FLDS_MARKER));

FLDS_TEXT = {'Visible' 'FontSize' 'FontAngle'};
sTxt = [s.TextProps]';
sTxt = structrestrictflds(sTxt,FLDS_TEXT);
sTxt = orderfields(sTxt,FLDS_TEXT);
tTxt = struct2table(sTxt);
%assert(isequal(tTxt.Properties.VariableNames,FLDS_TEXT));
tTxt.Visible = strcmp(tTxt.Visible,'on');

txtOffset = num2cell([s.TextOffset]');

assert(isequal(uitbl.ColumnName,...
  {'Marker' 'MarkerSize' 'LineWidth' 'Show Text Label' 'Label Font Size' 'Label Font Angle' 'Label Offset'}'));

dat = [table2cell(tMrkr) table2cell(tTxt) txtOffset];
uitbl.Data = dat;

function s = MarkerControlsGet(handles)
% Read handles.tblProps into various PV-structs etc that can be used to set
% HG handles.
%
% s: structarr of PV structs
% 
% s(i).pvLine -- PV struct for line handle
% s(i).pvTxt -- PV struct for text label
% s(i).txtOffset -- text offset (in px)
% Els of s labeled by lbl, pred, imp

uitbl = handles.tblProps;
assert(isequal(uitbl.RowName,{'Label', 'Prediction'}'));

uitblColumnNameSanitized = regexprep(uitbl.ColumnName,' ','_'); % for eg ML19a
t = cell2table(uitbl.Data,'VariableNames',uitblColumnNameSanitized);

FLDS_MARKER = {'Marker' 'MarkerSize' 'LineWidth'};
tLine = t(:,FLDS_MARKER);
sLine = table2struct(tLine);
% s = struct();
% s.pvLine = sLine;

FLDS_TEXT = {'Show_Text_Label','Label_Font_Size' 'Label_Font_Angle'};
tTxt = t(:,FLDS_TEXT);
tTxt.Properties.VariableNames = {'Visible' 'FontSize' 'FontAngle'};
tTxt.Visible = arrayfun(@onIff,tTxt.Visible,'uni',0);
sTxt = table2struct(tTxt);
% s.pvTxt = sTxt;

txtOffset = t{:,'Label_Offset'};

s = struct(...
  'landmarkSetType',num2cell(enumeration('LandmarkSetType')),...
  'MarkerProps',num2cell(sLine),...
  'TextProps',num2cell(sTxt),...
  'TextOffset',num2cell(txtOffset) ...
  );

%%%%%%%%%%%%
% SKELETON
%%%%%%%%%%%%
function SkelControlsSet(handles,s)
s1 = s(1).SkeletonProps;
handles.pbSkeletonColor.BackgroundColor = s1.Color;
handles.sldSkeletonLineWidth.Value = log2(s1.LineWidth);

function s = SkelControlsGet(handles)
s0 = struct();
s0.Color = handles.pbSkeletonColor.BackgroundColor;
s0.LineWidth = 2^handles.sldSkeletonLineWidth.Value;
s = struct(...
  'landmarkSetType',num2cell(enumeration('LandmarkSetType')),...
  'SkeletonProps',s0);


%%%%%%%%%%%%%%%%%%
% APPLY/DONE/ETC %
%%%%%%%%%%%%%%%%%%

function handles = SaveState(handles)

tfApplyAll = handles.cbApplyAll.Value;
iCS = handles.pumShowing.Value;
if tfApplyAll
  colorSpecs = handles.colorSpecs;
  for i=1:numel(colorSpecs)
    if i==iCS
      continue;
    end
    colorSpecs(i).copyColorState(colorSpecs(iCS));
  end
  colorSpecs0 = handles.colorSpecs0;
else
  colorSpecs = handles.colorSpecs(iCS);
  colorSpecs0 = handles.colorSpecs0(iCS);
end
colorSpecs.setManualColorsToColormapIfNec();
sPropsMrkr = MarkerControlsGet(handles);
sPropsSkel = SkelControlsGet(handles);

tfclrchanged = ~arrayfun(@isequal,colorSpecs,colorSpecs0);
% We do something convoluted here as handles.sPropsMrkr0 might have
% properties that are not visible/editable in the UI
tfmkrchanged = ~arrayfun(@(x,y)isequaln(x,structoverlay(x,y)),...
  handles.sPropsMrkr0,sPropsMrkr);
tfskelchanged = ~arrayfun(@(x,y)isequaln(x,structoverlay(x,y)),...
  handles.sPropsSkel0,sPropsSkel);

%~arrayfun(@isequaln,sPropsMrkr,handles.sPropsMrkr0);
handles.saved = struct(...
  'colorSpecs',colorSpecs(tfclrchanged),...  
  'markerSpecs',sPropsMrkr(tfmkrchanged),...
  'skeletonSpecs',sPropsSkel(tfskelchanged) ...
  );
% Note either field of handles.saved could be empty

function varargout = LandmarkColors_export_OutputFcn(hObject, eventdata, handles) 
% [tfchanges,savedinfo] = LandmarkColors_export(...)

if isempty(handles),
  warning('State lost');
  varargout{1} = false;
  varargout{2} = [];
else
  varargout{1} = ~isempty(handles.saved);
  varargout{2} = handles.saved;
  delete(handles.figure_landmarkcolors);
end

function figure_landmarkcolors_CloseRequestFcn(hObject, eventdata)
uiresume(hObject);

function pbApply_Callback(hObject, eventdata, handles)
handles = SaveState(handles);
saved = handles.saved;
handles.applyCbkFcn(saved.colorSpecs,saved.markerSpecs,saved.skeletonSpecs);
guidata(hObject,handles);

function pbCancel_Callback(hObject, eventdata, handles)
uiresume(handles.figure_landmarkcolors);

function pbDone_Callback(hObject, eventdata, handles)
handles = SaveState(handles);
guidata(hObject,handles);
uiresume(handles.figure_landmarkcolors);

function sldSkeletonLineWidth_Callback(hObject, eventdata, handles)
pbApply_Callback(handles.output,[],handles);

function sldSkeletonLineWidth_CreateFcn(hObject, eventdata, handles)
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end

function pbSkeletonColor_Callback(hObject, eventdata, handles)
c0 = handles.pbSkeletonColor.BackgroundColor;
handles.pbSkeletonColor.BackgroundColor = uisetcolor(c0);
pbApply_Callback(handles.output,[],handles);


% --- Creates and returns a handle to the GUI figure. 
function h1 = LandmarkColors_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 23, ...
    'radiobutton', 4, ...
    'uibuttongroup', 2, ...
    'popupmenu', 5, ...
    'axes', 2, ...
    'pushbutton', 10, ...
    'uipanel', 7, ...
    'slider', 4, ...
    'edit', 10, ...
    'checkbox', 5, ...
    'uitable', 3), ...
    'override', 1, ...
    'release', [], ...
    'resize', 'simple', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', '/home/taylora@hhmi.org/apt-local/tp3/apt/matlab/LandmarkColors_export.m', ...
    'lastFilename', '/dat0/git/apt.multianimal.clean/matlab/LandmarkColors.fig');
appdata.lastValidTag = 'figure_landmarkcolors';

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units',get(0,'defaultfigureUnits'),...
'Position',[951.6 770.153846153846 464 575],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'Colormap',get(0,'defaultfigureColormap'),...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar',get(0,'defaultfigureToolBar'),...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','LandmarkColors',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','figure_landmarkcolors',...
'UserData',[],...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'pbDone';

h2 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Done',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[180 5 97 26],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)LandmarkColors_export('pbDone_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pbDone',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pnlTab';

h3 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title',blanks(0),...
'Tag','pnlTab',...
'Position',[0 34 466 541],...
'Layout',[],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uibuttongroup1';

h4 = uibuttongroup(...
'Parent',h3,...
'FontUnits','points',...
'Units','pixels',...
'SelectionChangeFcn',blanks(0),...
'ForegroundColor',[0 0 0],...
'HighlightColor',[1 1 1],...
'ShadowColor',[0.7 0.7 0.7],...
'BorderType','etchedin',...
'BorderWidth',1,...
'TitlePosition','lefttop',...
'Title','Colors',...
'Visible','on',...
'BackgroundColor',[0.94 0.94 0.94],...
'ResizeFcn',blanks(0),...
'HandleVisibility','on',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uibuttongroup1',...
'UserData',[],...
'Position',[5 267 454 269],...
'Layout',[],...
'FontSize',10,...
'FontName','Helvetica',...
'FontAngle','italic',...
'FontWeight','normal');

appdata = [];
appdata.lastValidTag = 'radiobutton_colormap';

h5 = uicontrol(...
'Parent',h4,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Colormap',...
'Style','radiobutton',...
'Value',1,...
'Position',[15 197 107 36],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)LandmarkColors_export('radiobutton_colormap_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','radiobutton_colormap',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'uipanel_manual';

h6 = uipanel(...
'Parent',h4,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel_manual',...
'UserData',[],...
'Position',[36 18 378 43],...
'Layout',[],...
'FontSize',0.296296296296296,...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'uipanel_colormap';

h7 = uipanel(...
'Parent',h4,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType','none',...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel_colormap',...
'UserData',[],...
'Position',[35 96 379 98],...
'Layout',[],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'axes_colormap';

h8 = axes(...
'Parent',h7,...
'FontUnits','normalized',...
'Units',get(0,'defaultaxesUnits'),...
'View',get(0,'defaultaxesView'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'Projection',get(0,'defaultaxesProjection'),...
'LabelFontSizeMultiplier',get(0,'defaultaxesLabelFontSizeMultiplier'),...
'AmbientLightColor',get(0,'defaultaxesAmbientLightColor'),...
'PlotBoxAspectRatio',[1 0.15018315018315 0.15018315018315],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'FontName',get(0,'defaultaxesFontName'),...
'FontAngle',get(0,'defaultaxesFontAngle'),...
'FontWeight',get(0,'defaultaxesFontWeight'),...
'FontSmoothing',get(0,'defaultaxesFontSmoothing'),...
'TickLabelInterpreter',get(0,'defaultaxesTickLabelInterpreter'),...
'XDir',get(0,'defaultaxesXDir'),...
'YDir',get(0,'defaultaxesYDir'),...
'ZDir',get(0,'defaultaxesZDir'),...
'Layer',get(0,'defaultaxesLayer'),...
'TickLength',get(0,'defaultaxesTickLength'),...
'GridLineStyle',get(0,'defaultaxesGridLineStyle'),...
'MinorGridLineStyle',get(0,'defaultaxesMinorGridLineStyle'),...
'XAxisLocation',get(0,'defaultaxesXAxisLocation'),...
'XTick',[0 0.2 0.4 0.6 0.8 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabelRotation',get(0,'defaultaxesXTickLabelRotation'),...
'XScale',get(0,'defaultaxesXScale'),...
'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'XMinorTick',get(0,'defaultaxesXMinorTick'),...
'YAxisLocation',get(0,'defaultaxesYAxisLocation'),...
'YTick',[0 0.5 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabelRotation',get(0,'defaultaxesYTickLabelRotation'),...
'YScale',get(0,'defaultaxesYScale'),...
'YTickLabel',{  '0'; '0.5'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'YMinorTick',get(0,'defaultaxesYMinorTick'),...
'ZTickLabelRotation',get(0,'defaultaxesZTickLabelRotation'),...
'ZScale',get(0,'defaultaxesZScale'),...
'ZMinorTick',get(0,'defaultaxesZMinorTick'),...
'BoxStyle',get(0,'defaultaxesBoxStyle'),...
'LineWidth',get(0,'defaultaxesLineWidth'),...
'Color',get(0,'defaultaxesColor'),...
'ClippingStyle',get(0,'defaultaxesClippingStyle'),...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'TitleMode',get(0,'defaultaxesTitleMode'),...
'SubtitleMode',get(0,'defaultaxesSubtitleMode'),...
'BoxFrame',[],...
'BoxFrameMode',get(0,'defaultaxesBoxFrameMode'),...
'XAxisMode','manual',...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZAxisMode','manual',...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'Box',get(0,'defaultaxesBox'),...
'XGrid',get(0,'defaultaxesXGrid'),...
'XMinorGrid',get(0,'defaultaxesXMinorGrid'),...
'YGrid',get(0,'defaultaxesYGrid'),...
'YMinorGrid',get(0,'defaultaxesYMinorGrid'),...
'ZGrid',get(0,'defaultaxesZGrid'),...
'ZMinorGrid',get(0,'defaultaxesZMinorGrid'),...
'Position',[0.0131926121372032 0.173469387755102 0.720316622691293 0.418367346938776],...
'InnerPosition',[0.0131926121372032 0.173469387755102 0.720316622691293 0.418367346938776],...
'InnerPositionMode',get(0,'defaultaxesInnerPositionMode'),...
'ActivePositionProperty','position',...
'PositionConstraint','innerposition',...
'PositionConstraintMode',get(0,'defaultaxesPositionConstraintMode'),...
'LooseInset',[0.174844333748443 0.399511674042423 0.127770859277709 0.272394323210743],...
'LooseInsetMode',get(0,'defaultaxesLooseInsetMode'),...
'Alphamap',[0 0.0159 0.0317 0.0476 0.0635 0.0794 0.0952 0.1111 0.127 0.1429 0.1587 0.1746 0.1905 0.2063 0.2222 0.2381 0.254 0.2698 0.2857 0.3016 0.3175 0.3333 0.3492 0.3651 0.381 0.3968 0.4127 0.4286 0.4444 0.4603 0.4762 0.4921 0.5079 0.5238 0.5397 0.5556 0.5714 0.5873 0.6032 0.619 0.6349 0.6508 0.6667 0.6825 0.6984 0.7143 0.7302 0.746 0.7619 0.7778 0.7937 0.8095 0.8254 0.8413 0.8571 0.873 0.8889 0.9048 0.9206 0.9365 0.9524 0.9683 0.9841 1],...
'AlphamapMode',get(0,'defaultaxesAlphamapMode'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'ColorOrderIndex',get(0,'defaultaxesColorOrderIndex'),...
'LineStyleOrder',get(0,'defaultaxesLineStyleOrder'),...
'LineStyleOrderIndex',get(0,'defaultaxesLineStyleOrderIndex'),...
'FontSize',0.310077519379845,...
'TitleFontWeight',get(0,'defaultaxesTitleFontWeight'),...
'TitleFontSizeMultiplier',get(0,'defaultaxesTitleFontSizeMultiplier'),...
'SortMethod','childorder',...
'Clipping',get(0,'defaultaxesClipping'),...
'NextPlot',get(0,'defaultaxesNextPlot'),...
'ChildrenMode','manual',...
'Visible',get(0,'defaultaxesVisible'),...
'HandleVisibility',get(0,'defaultaxesHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','axes_colormap',...
'UserData',[],...
'HitTest',get(0,'defaultaxesHitTest'),...
'PickableParts',get(0,'defaultaxesPickableParts'),...
'Title',[]);

h9 = get(h8,'title');

set(h9,...
'Parent',h8,...
'Units','data',...
'FontUnits','normalized',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000497797033 1.06395348837209 0.5],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',0.341085271317829,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','bold',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','off',...
'XLimIncludeMode','auto',...
'YLimInclude','off',...
'YLimIncludeMode','auto',...
'ZLimInclude','off',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'SeriesIndex','none',...
'SeriesIndexMode','auto');

h10 = get(h8,'xlabel');

set(h10,...
'Parent',h8,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0.500000476837158 -0.502741528140009 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',10.4883720930233,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','off',...
'XLimIncludeMode','auto',...
'YLimInclude','off',...
'YLimIncludeMode','auto',...
'ZLimInclude','off',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'SeriesIndex','none',...
'SeriesIndexMode','auto');

h11 = get(h8,'ylabel');

set(h11,...
'Parent',h8,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[-0.0951245117641767 0.500000476837158 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',10.4883720930233,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','off',...
'XLimIncludeMode','auto',...
'YLimInclude','off',...
'YLimIncludeMode','auto',...
'ZLimInclude','off',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'SeriesIndex','none',...
'SeriesIndexMode','auto');

h12 = get(h8,'zlabel');

set(h12,...
'Parent',h8,...
'Units','data',...
'FontUnits','normalized',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0 0 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',0.310077519379845,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','middle',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','off',...
'XLimIncludeMode','auto',...
'YLimInclude','off',...
'YLimIncludeMode','auto',...
'ZLimInclude','off',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','off',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'SeriesIndex','none',...
'SeriesIndexMode','auto');

appdata = [];
appdata.lastValidTag = 'popupmenu_colormap';

h13 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'jet'; 'parula'; 'hsv'; 'lines'; 'autumn'; 'spring'; 'winter'; 'summer'; 'hot'; 'cool' },...
'Style','popupmenu',...
'Value',1,...
'Position',[0.0128205128205128 0.669902912621359 0.387179487179487 0.213592233009709],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)LandmarkColors_export('popupmenu_colormap_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)LandmarkColors_export('popupmenu_colormap_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','popupmenu_colormap',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'slider_brightness';

h14 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'Slider' },...
'Style','slider',...
'Value',0.5,...
'Position',[0.775725593667546 0.214285714285714 0.058047493403694 0.673469387755102],...
'BackgroundColor',[0.9 0.9 0.9],...
'Callback',@(hObject,eventdata)LandmarkColors_export('slider_brightness_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)LandmarkColors_export('slider_brightness_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','slider_brightness');

appdata = [];
appdata.lastValidTag = 'edit_brightness';

h15 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','0.50',...
'Style','edit',...
'Value',0.5,...
'Position',[0.759894459102902 -0.0306122448979592 0.0897097625329816 0.214285714285714],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)LandmarkColors_export('edit_brightness_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)LandmarkColors_export('edit_brightness_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit_brightness');

appdata = [];
appdata.lastValidTag = 'text2';

h16 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Light',...
'Style','text',...
'Position',[0.846965699208443 0.704081632653061 0.102902374670185 0.163265306122449],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text2',...
'FontAngle','italic');

appdata = [];
appdata.lastValidTag = 'text3';

h17 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Dark',...
'Style','text',...
'Position',[0.849604221635884 0.183673469387755 0.102902374670185 0.163265306122449],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text3',...
'FontAngle','italic');

appdata = [];
appdata.lastValidTag = 'radiobutton_manual';

h18 = uicontrol(...
'Parent',h4,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Manual',...
'Style','radiobutton',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[15 66 107 36],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)LandmarkColors_export('radiobutton_manual_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','radiobutton_manual',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pumShowing';

h19 = uicontrol(...
'Parent',h4,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'Labels'; 'Predictions'; 'Imported' },...
'Style','popupmenu',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[0.58 0.838582677165354 0.397777777777778 0.0787401574803149],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)LandmarkColors_export('pumShowing_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)LandmarkColors_export('pumShowing_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','pumShowing',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'text12';

h20 = uicontrol(...
'Parent',h4,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Showing colors for:',...
'Style','text',...
'Position',[0.311111111111111 0.84251968503937 0.257777777777778 0.0551181102362205],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text12',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'cbApplyAll';

h21 = uicontrol(...
'Parent',h4,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','checkbox',...
'Position',[0.944444444444444 0.921259842519685 0.04 0.0905511811023622],...
'Callback',blanks(0),...
'Children',[],...
'Tag','cbApplyAll',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text19';

h22 = uicontrol(...
'Parent',h4,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Apply colors to labels, predictions, imported',...
'Style','text',...
'Position',[0.34 0.940944881889764 0.595555555555555 0.0551181102362205],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text19',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'pnlMarkersLabels';

h23 = uipanel(...
'Parent',h3,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Markers and Labels',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pnlMarkersLabels',...
'Position',[5 104 454 161],...
'Layout',[],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontAngle','italic');

appdata = [];
appdata.lastValidTag = 'tblProps';
appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [4 2] [4 7] 'DataDefault' [2 3] {  'Marker' 'MarkerSize' 'LineWidth' 'Show Text Label' 'Label Font Size' 'Label Font Angle' 'Label Offset' } {  'Label' 'Prediction' 'Imported' blanks(0) } } };

h24 = uitable(...
'Parent',h23,...
'Units','normalized',...
'FontUnits',get(0,'defaultuitableFontUnits'),...
'BackgroundColor',get(0,'defaultuitableBackgroundColor'),...
'ColumnName',{  'Marker'; 'MarkerSize'; 'LineWidth'; 'Show Text Label'; 'Label Font Size'; 'Label Font Angle'; 'Label Offset' },...
'ColumnWidth',{  'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto' },...
'Data',{  blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0); blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0); blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0); blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) blanks(0) },...
'RowName',{  'Label'; 'Prediction'; 'Imported'; blanks(0) },...
'ColumnSortable',[],...
'Position',[0.0266666666666667 0.0684931506849315 0.96 0.863013698630137],...
'ColumnEditable',[true true true true true true true],...
'ColumnFormat',{  [] [] [] [] [] [] [] },...
'RearrangeableColumns',get(0,'defaultuitableRearrangeableColumns'),...
'RowStriping',get(0,'defaultuitableRowStriping'),...
'CellEditCallback',blanks(0),...
'CellSelectionCallback',blanks(0),...
'DisplayDataChangedFcn',blanks(0),...
'Children',[],...
'Selection',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuitableForegroundColor'),...
'Enable',get(0,'defaultuitableEnable'),...
'Visible',get(0,'defaultuitableVisible'),...
'HandleVisibility',get(0,'defaultuitableHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','tblProps',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuitableFontName'),...
'FontAngle',get(0,'defaultuitableFontAngle'),...
'FontWeight',get(0,'defaultuitableFontWeight'),...
'Layout',[]);

appdata = [];
appdata.lastValidTag = 'uipanel6';

h25 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Tooltip',blanks(0),...
'Enable',get(0,'defaultuipanelEnable'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title','Skeleton',...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel6',...
'UserData',[],...
'Position',[5 44 455 95],...
'Layout',[],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle','italic',...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'sldSkeletonLineWidth';

h26 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'Slider' },...
'Style','slider',...
'Position',[0.454545454545455 0.2375 0.25 0.2125],...
'BackgroundColor',[0.9 0.9 0.9],...
'Callback',@(hObject,eventdata)LandmarkColors_export('sldSkeletonLineWidth_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)LandmarkColors_export('sldSkeletonLineWidth_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','sldSkeletonLineWidth');

appdata = [];
appdata.lastValidTag = 'text21';

h27 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Thickness:',...
'Style','text',...
'Position',[0.164079822616408 0.225 0.266075388026608 0.2125],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text21',...
'FontAngle',get(0,'defaultuicontrolFontAngle'));

appdata = [];
appdata.lastValidTag = 'pbSkeletonColor';

h28 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.452328159645233 0.55 0.25 0.2625],...
'Callback',@(hObject,eventdata)LandmarkColors_export('pbSkeletonColor_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pbSkeletonColor',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text22';

h29 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Color:',...
'Style','text',...
'Position',[0.164079822616408 0.55 0.266075388026608 0.2125],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text22',...
'FontAngle',get(0,'defaultuicontrolFontAngle'));


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % LANDMARKCOLORS_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % LANDMARKCOLORS_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % LANDMARKCOLORS_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % LANDMARKCOLORS_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


