classdef LandmarkColorsController < handle
  % Controller for the "Landmark Cosmetics" dialog (keypoint appearance:
  % per-landmark colors, marker/label properties, and skeleton cosmetics).
  %
  % This replaces the legacy GUIDE app LandmarkColors.m / LandmarkColors.fig.
  % The figure is built programmatically in createGui_() (layout lifted from
  % GUIDE's export), the widget handles live as instance properties (no more
  % guidata reach-throughs), and the dialog is modal but non-blocking (no
  % uiwait): edits are applied to the model live via the apply callback, so the
  % constructor returns immediately.

  properties (Transient)
    hFig  % the dialog figure
    parent_  % a LabelerController
    labeler_  % a Labeler
    applyCbkFcn_  % cbk(colorSpecs, markerSpecs, skeletonSpecs)

    % State (formerly stored in guidata)
    nlandmarks_
    colorSpecs_  % array of LandmarkColorSpec; live color state, edited in place
    colorSpecs0_  % copy of colorSpecs_ at open, for change detection
    sPropsMrkr0_  % marker/label state at open, for change detection
    sPropsSkel0_  % skeleton state at open, for change detection
    colormapim_  % image handle in the colormap-preview axes
    hbuttons_  % [1 x nlandmarks] per-landmark manual-color pushbuttons
    hSldListener_  % listener on the skeleton-line-width slider's ContinuousValueChange
    saved_  % struct of changed specs, set by saveState_()

    % Widget handles, formerly reached via guidata(obj.hFig).
    pbDone_
    pnlTab_
    uibuttongroup1_  % the "Colors" button group (colormap vs. manual)
    radiobutton_colormap_
    radiobutton_manual_
    uipanel_manual_
    uipanel_colormap_
    axes_colormap_
    popupmenu_colormap_
    slider_brightness_
    edit_brightness_
    pumShowing_
    cbApplyAll_
    pnlMarkersLabels_
    tblProps_
    uipanel6_  % the "Skeleton" panel
    sldSkeletonLineWidth_
    pbSkeletonColor_
  end  % properties

  methods
    function obj = LandmarkColorsController(parent, labeler, applyCbkFcn)
      % Build the dialog and initialize its state from the Labeler.
      % applyCbkFcn signature: cbk(colorSpecs, markerSpecs, skeletonSpecs).
      obj.parent_ = parent ;
      obj.labeler_ = labeler ;
      obj.applyCbkFcn_ = applyCbkFcn ;
      obj.nlandmarks_ = labeler.nPhysPoints ;

      obj.createGui_() ;

      % Marker state -- lives only in the table; get/set via markerControls*_.
      lsetTypesCell = num2cell(enumeration('LandmarkSetType')) ;
      ppiAll = {labeler.labelPointsPlotInfo ; labeler.predPointsPlotInfo} ;
      FLDS = {'MarkerProps' 'TextProps' 'TextOffset'} ;
      sPropsMrkr = cellfun(@(x)structrestrictflds(x,FLDS), ppiAll) ;
      [sPropsMrkr.landmarkSetType] = deal(lsetTypesCell{:}) ;
      % Color state -- maintained in obj.colorSpecs_; the Colors pane shows the
      % spec selected by pumShowing_.
      lsetTypesCellCount = numel(lsetTypesCell) ;
      obj.colorSpecs_ = ...
        cellfun(@(x1,x2,x3)LandmarkColorSpec(x1,x2,x3), ...
                lsetTypesCell, ...
                repmat({labeler.nPhysPoints}, lsetTypesCellCount, 1), ...
                ppiAll) ;
      % Skeleton state
      FLDS = {'SkeletonProps'} ;
      sPropsSkel = cellfun(@(x)structrestrictflds(x,FLDS), ppiAll) ;
      [sPropsSkel.landmarkSetType] = deal(lsetTypesCell{:}) ;

      obj.sPropsMrkr0_ = sPropsMrkr ;
      obj.colorSpecs0_ = obj.colorSpecs_.copy() ;
      obj.sPropsSkel0_ = sPropsSkel ;

      obj.initColorsPane_() ;
      obj.updateColorsPane_() ;

      MARKERS = num2cell('o+*.xsd^v><ph') ;
      tbl = obj.tblProps_ ;
      tbl.ColumnFormat{1} = MARKERS ;
      tbl.ColumnFormat{6} = {'normal' 'italic'} ;
      ncol = numel(tbl.ColumnFormat) ;
      set(tbl, 'Data', cell(3,ncol), 'RowName', {'Label' 'Prediction'}) ;

      obj.markerControlsSet_(sPropsMrkr) ;

      obj.sldSkeletonLineWidth_.Min = -1 ;  % log scale
      obj.sldSkeletonLineWidth_.Max = 5 ;
      obj.hSldListener_ = ...
        addlistener(obj.sldSkeletonLineWidth_, 'ContinuousValueChange', ...
                    @(s,e)(obj.sldSkeletonLineWidthActuated_())) ;
      obj.skelControlsSet_(sPropsSkel) ;

      obj.saved_ = [] ;
      obj.tblProps_.CellEditCallback = @(s,e)(obj.tblCellEditActuated_()) ;
    end  % function

    function delete(obj)
      % Tear down the listener and figure.
      if ~isempty(obj.hSldListener_) && isvalid(obj.hSldListener_)
        delete(obj.hSldListener_) ;
      end
      deleteValidGraphicsHandles(obj.hFig) ;
      obj.hFig = [] ;
    end  % function

    function createGui_(obj)
      % Build the dialog figure and its widgets programmatically, storing the
      % widget handles as instance properties.  Layout lifted from GUIDE's
      % export of LandmarkColors.fig.
      obj.hFig = figure(...
        'Units', 'pixels', ...
        'Position', [951.6 770.153846153846 464 575], ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'DockControls', 'off', ...
        'NumberTitle', 'off', ...
        'IntegerHandle', 'off', ...
        'Name', 'Landmark Cosmetics', ...
        'WindowStyle', 'modal', ...
        'Tag', 'figure_landmarkcolors', ...
        'CloseRequestFcn', @(s,e)(obj.closeRequested_())) ;

      obj.pbDone_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'pixels', ...
        'String', 'Done', ...
        'Position', [180 5 97 26], ...
        'FontSize', 9, ...
        'Tag', 'pbDone', ...
        'Callback', @(s,e)(obj.doneActuated_())) ;

      obj.pnlTab_ = uipanel(...
        'Parent', obj.hFig, ...
        'Units', 'pixels', ...
        'Title', '', ...
        'Position', [0 34 466 541], ...
        'FontSize', 8, ...
        'Tag', 'pnlTab') ;

      obj.uibuttongroup1_ = uibuttongroup(...
        'Parent', obj.pnlTab_, ...
        'Units', 'pixels', ...
        'Title', 'Colors', ...
        'ForegroundColor', [0 0 0], ...
        'BackgroundColor', [0.94 0.94 0.94], ...
        'Position', [5 267 454 269], ...
        'FontSize', 10, ...
        'FontAngle', 'italic', ...
        'FontWeight', 'normal', ...
        'Tag', 'uibuttongroup1') ;

      obj.radiobutton_colormap_ = uicontrol(...
        'Parent', obj.uibuttongroup1_, ...
        'Style', 'radiobutton', ...
        'Units', 'pixels', ...
        'String', 'Colormap', ...
        'Value', 1, ...
        'Position', [15 197 107 36], ...
        'FontSize', 8, ...
        'Tag', 'radiobutton_colormap', ...
        'Callback', @(s,e)(obj.radiobuttonColormapActuated_())) ;

      obj.uipanel_colormap_ = uipanel(...
        'Parent', obj.uibuttongroup1_, ...
        'Units', 'pixels', ...
        'Title', '', ...
        'Position', [35 96 379 98], ...
        'Tag', 'uipanel_colormap') ;

      obj.uipanel_manual_ = uipanel(...
        'Parent', obj.uibuttongroup1_, ...
        'Units', 'pixels', ...
        'Title', '', ...
        'Position', [36 18 378 43], ...
        'Tag', 'uipanel_manual') ;

      obj.axes_colormap_ = axes(...
        'Parent', obj.uipanel_colormap_, ...
        'Units', 'normalized', ...
        'Position', [0.0131926121372032 0.173469387755102 0.720316622691293 0.418367346938776], ...
        'Tag', 'axes_colormap') ;

      obj.popupmenu_colormap_ = uicontrol(...
        'Parent', obj.uipanel_colormap_, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'String', {'jet' ; 'parula' ; 'hsv' ; 'lines' ; 'autumn' ; 'spring' ; 'winter' ; 'summer' ; 'hot' ; 'cool'}, ...
        'Value', 1, ...
        'Position', [0.0128205128205128 0.669902912621359 0.387179487179487 0.213592233009709], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 8, ...
        'Tag', 'popupmenu_colormap', ...
        'Callback', @(s,e)(obj.popupmenuColormapActuated_())) ;

      obj.slider_brightness_ = uicontrol(...
        'Parent', obj.uipanel_colormap_, ...
        'Style', 'slider', ...
        'Units', 'normalized', ...
        'Value', 0.5, ...
        'Position', [0.775725593667546 0.214285714285714 0.058047493403694 0.673469387755102], ...
        'BackgroundColor', [0.9 0.9 0.9], ...
        'Tag', 'slider_brightness', ...
        'Callback', @(s,e)(obj.sliderBrightnessActuated_())) ;

      obj.edit_brightness_ = uicontrol(...
        'Parent', obj.uipanel_colormap_, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'String', '0.50', ...
        'Value', 0.5, ...
        'Position', [0.759894459102902 -0.0306122448979592 0.0897097625329816 0.214285714285714], ...
        'BackgroundColor', [1 1 1], ...
        'Tag', 'edit_brightness', ...
        'Callback', @(s,e)(obj.editBrightnessActuated_())) ;

      uicontrol(...
        'Parent', obj.uipanel_colormap_, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'String', 'Light', ...
        'Position', [0.846965699208443 0.704081632653061 0.102902374670185 0.163265306122449], ...
        'FontAngle', 'italic', ...
        'Tag', 'text2') ;

      uicontrol(...
        'Parent', obj.uipanel_colormap_, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'String', 'Dark', ...
        'Position', [0.849604221635884 0.183673469387755 0.102902374670185 0.163265306122449], ...
        'FontAngle', 'italic', ...
        'Tag', 'text3') ;

      obj.radiobutton_manual_ = uicontrol(...
        'Parent', obj.uibuttongroup1_, ...
        'Style', 'radiobutton', ...
        'Units', 'pixels', ...
        'String', 'Manual', ...
        'Position', [15 66 107 36], ...
        'FontSize', 8, ...
        'Tag', 'radiobutton_manual', ...
        'Callback', @(s,e)(obj.radiobuttonManualActuated_())) ;

      obj.pumShowing_ = uicontrol(...
        'Parent', obj.uibuttongroup1_, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'String', {'Labels' ; 'Predictions' ; 'Imported'}, ...
        'Value', 1, ...
        'Position', [0.58 0.838582677165354 0.397777777777778 0.0787401574803149], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 8, ...
        'Tag', 'pumShowing', ...
        'Callback', @(s,e)(obj.pumShowingActuated_())) ;

      uicontrol(...
        'Parent', obj.uibuttongroup1_, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Showing colors for:', ...
        'Position', [0.311111111111111 0.84251968503937 0.257777777777778 0.0551181102362205], ...
        'FontSize', 8, ...
        'Tag', 'text12') ;

      obj.cbApplyAll_ = uicontrol(...
        'Parent', obj.uibuttongroup1_, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'String', '', ...
        'Position', [0.944444444444444 0.921259842519685 0.04 0.0905511811023622], ...
        'FontSize', 8, ...
        'Tag', 'cbApplyAll') ;

      uicontrol(...
        'Parent', obj.uibuttongroup1_, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Apply colors to labels, predictions, imported', ...
        'Position', [0.34 0.940944881889764 0.595555555555555 0.0551181102362205], ...
        'FontSize', 8, ...
        'Tag', 'text19') ;

      obj.pnlMarkersLabels_ = uipanel(...
        'Parent', obj.pnlTab_, ...
        'Units', 'pixels', ...
        'Title', 'Markers and Labels', ...
        'Position', [5 104 454 161], ...
        'FontAngle', 'italic', ...
        'Tag', 'pnlMarkersLabels') ;

      obj.tblProps_ = uitable(...
        'Parent', obj.pnlMarkersLabels_, ...
        'Units', 'normalized', ...
        'ColumnName', {'Marker' ; 'MarkerSize' ; 'LineWidth' ; 'Show Text Label' ; 'Label Font Size' ; 'Label Font Angle' ; 'Label Offset'}, ...
        'ColumnWidth', {'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto'}, ...
        'ColumnEditable', [true true true true true true true], ...
        'ColumnFormat', {[] [] [] [] [] [] []}, ...
        'Position', [0.0266666666666667 0.0684931506849315 0.96 0.863013698630137], ...
        'FontSize', 8, ...
        'Tag', 'tblProps') ;

      obj.uipanel6_ = uipanel(...
        'Parent', obj.hFig, ...
        'Units', 'pixels', ...
        'Title', 'Skeleton', ...
        'Position', [5 44 455 95], ...
        'FontAngle', 'italic', ...
        'Tag', 'uipanel6') ;

      obj.sldSkeletonLineWidth_ = uicontrol(...
        'Parent', obj.uipanel6_, ...
        'Style', 'slider', ...
        'Units', 'normalized', ...
        'Position', [0.454545454545455 0.2375 0.25 0.2125], ...
        'BackgroundColor', [0.9 0.9 0.9], ...
        'Tag', 'sldSkeletonLineWidth', ...
        'Callback', @(s,e)(obj.sldSkeletonLineWidthActuated_())) ;

      uicontrol(...
        'Parent', obj.uipanel6_, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Thickness:', ...
        'Position', [0.164079822616408 0.225 0.266075388026608 0.2125], ...
        'Tag', 'text21') ;

      obj.pbSkeletonColor_ = uicontrol(...
        'Parent', obj.uipanel6_, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'String', '', ...
        'Position', [0.452328159645233 0.55 0.25 0.2625], ...
        'Tag', 'pbSkeletonColor', ...
        'Callback', @(s,e)(obj.pbSkeletonColorActuated_())) ;

      uicontrol(...
        'Parent', obj.uipanel6_, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Color:', ...
        'Position', [0.164079822616408 0.55 0.266075388026608 0.2125], ...
        'Tag', 'text22') ;

      % Center on the main APT window.
      if ~isempty(obj.parent_)
        mainFigurePosition = obj.parent_.mainFigurePixelPosition() ;
        centerOnOtherFigureGivenPositionBang(obj.hFig, mainFigurePosition) ;
      end
    end  % function

    %%%%%%%%%%
    % COLORS %
    %%%%%%%%%%

    function initColorsPane_(obj)
      % Populate the static parts of the Colors pane (once, at open).
      pum = obj.pumShowing_ ;
      pum.String = {'Labels' ; 'Predictions'} ;
      pum.Value = 1 ;

      % Colormap pulldown options
      pum = obj.popupmenu_colormap_ ;
      cmapnames = LandmarkColorSpec.CMAPNAMES ;
      ncmapnames = numel(cmapnames) ;
      cmapname2idx = cell2struct(num2cell(1:ncmapnames), cmapnames, 2) ;
      set(pum, 'String', LandmarkColorSpec.CMAPNAMES, 'Value', 1, 'UserData', cmapname2idx) ;

      obj.colormapim_ = imagesc(1:obj.nlandmarks_, 'Parent', obj.axes_colormap_) ;
      axis(obj.axes_colormap_, 'off') ;

      % create per-landmark manual-color buttons
      w = 1/obj.nlandmarks_ ;
      borderfrac = .05 ;
      for i = 1:obj.nlandmarks_
        obj.hbuttons_(i) = uicontrol(...
          'style', 'pushbutton', ...
          'ForegroundColor', 'k', ...
          'BackgroundColor', [0.5 0.5 0.5], ...
          'Units', 'normalized', ...
          'Position', [w*borderfrac+w*(i-1), borderfrac, w*(1-2*borderfrac), 1-2*borderfrac], ...
          'Parent', obj.uipanel_manual_, ...
          'Callback', @(s,e)(obj.pushbuttonManualActuated_(i)), ...
          'Tag', sprintf('pushbutton_manual_%d', i), ...
          'String', num2str(i)) ;
      end
    end  % function

    function updateColorsPane_(obj)
      % Sync the Colors pane uicontrols to the currently-shown colorSpec.
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;

      % mode
      btnGrp = obj.radiobutton_manual_.Parent ;
      if cs.tfmanual
        btnGrp.SelectedObject = obj.radiobutton_manual_ ;
      else
        btnGrp.SelectedObject = obj.radiobutton_colormap_ ;
      end

      obj.updateColorMode_() ;

      if cs.tfmanual
        % manual button colors
        for i = 1:obj.nlandmarks_
          set(obj.hbuttons_(i), 'BackgroundColor', cs.colors(i,:)) ;
        end
      else
        % colormapname
        cmapname = cs.colormapname ;
        pumcmap = obj.popupmenu_colormap_ ;
        cmapidx = pumcmap.UserData.(cmapname) ;
        pumcmap.Value = cmapidx ;

        % colormap
        colormap(obj.axes_colormap_, cs.colormap) ;

        % brightness
        set(obj.edit_brightness_, 'String', num2str(cs.brightness)) ;
        set(obj.slider_brightness_, 'Value', cs.brightness) ;
      end
    end  % function

    function updateColorMode_(obj)
      % Enable/disable colormap vs. manual panes based on the mode radiobutton.
      v = get(obj.radiobutton_manual_, 'Value') ;
      hcm = findobj(obj.uipanel_colormap_, '-property', 'Enable') ;
      hm = findobj(obj.uipanel_manual_, '-property', 'Enable') ;
      if v == 1
        set(hcm, 'Enable', 'off') ;
        set(hm, 'Enable', 'on') ;
      else
        set(hcm, 'Enable', 'on') ;
        set(hm, 'Enable', 'off') ;
      end
    end  % function

    function pumShowingActuated_(obj)
      obj.updateColorsPane_() ;
    end  % function

    function popupmenuColormapActuated_(obj)
      contents = cellstr(get(obj.popupmenu_colormap_, 'String')) ;
      cmapname = contents{get(obj.popupmenu_colormap_, 'Value')} ;
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;
      cs.setColormapName(cmapname) ;
      obj.updateColorsPane_() ;
      obj.applyActuated_() ;
    end  % function

    function sliderBrightnessActuated_(obj)
      v = get(obj.slider_brightness_, 'Value') ;
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;
      cs.setBrightness(v) ;
      obj.updateColorsPane_() ;
      obj.applyActuated_() ;
    end  % function

    function editBrightnessActuated_(obj)
      v = str2double(get(obj.edit_brightness_, 'String')) ;
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;
      if isnan(v) || v < 0 || v > 1
        warndlg('Brightness must be a number between 0 and 1', 'Error setting brightness', 'modal') ;
        set(obj.edit_brightness_, 'String', num2str(cs.brightness)) ;
      else
        cs.setBrightness(v) ;
        obj.updateColorsPane_() ;
        obj.applyActuated_() ;
      end
    end  % function

    function radiobuttonColormapActuated_(obj)
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;
      cs.setTFManual(false) ;
      obj.updateColorsPane_() ;
    end  % function

    function radiobuttonManualActuated_(obj)
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;
      cs.setManualColorsToColormap() ;
      cs.setTFManual(true) ;
      obj.updateColorsPane_() ;
    end  % function

    function pushbuttonManualActuated_(obj, landmarki)
      cs = obj.colorSpecs_(obj.pumShowing_.Value) ;
      clr = uisetcolor(cs.colors(landmarki,:), sprintf('Landmark %d color', landmarki)) ;
      % uisetcolor returns the empty array if the user cancels the dialog; in
      % that case leave the landmark color unchanged and do not re-apply.
      if isempty(clr)
        return ;
      end
      cs.setColorManual(landmarki, clr) ;
      obj.updateColorsPane_() ;
      obj.applyActuated_() ;
    end  % function

    %%%%%%%%%%%
    % MARKERS %
    %%%%%%%%%%%

    function markerControlsSet_(obj, s)
      % Set tblProps_ per the marker/label struct array s.
      uitbl = obj.tblProps_ ;
      assert(isequal(uitbl.RowName, {'Label' 'Prediction'}')) ;

      FLDS_MARKER = {'Marker' 'MarkerSize' 'LineWidth'} ;
      tMrkr = struct2table([s.MarkerProps]') ;
      assert(isequal(tMrkr.Properties.VariableNames, FLDS_MARKER)) ;

      FLDS_TEXT = {'Visible' 'FontSize' 'FontAngle'} ;
      sTxt = [s.TextProps]' ;
      sTxt = structrestrictflds(sTxt, FLDS_TEXT) ;
      sTxt = orderfields(sTxt, FLDS_TEXT) ;
      tTxt = struct2table(sTxt) ;
      tTxt.Visible = strcmp(tTxt.Visible, 'on') ;

      txtOffset = num2cell([s.TextOffset]') ;

      assert(isequal(uitbl.ColumnName, ...
        {'Marker' 'MarkerSize' 'LineWidth' 'Show Text Label' 'Label Font Size' 'Label Font Angle' 'Label Offset'}')) ;

      dat = [table2cell(tMrkr) table2cell(tTxt) txtOffset] ;
      uitbl.Data = dat ;
    end  % function

    function s = markerControlsGet_(obj)
      % Read tblProps_ into a struct array of PV-structs.
      uitbl = obj.tblProps_ ;
      assert(isequal(uitbl.RowName, {'Label', 'Prediction'}')) ;

      uitblColumnNameSanitized = regexprep(uitbl.ColumnName, ' ', '_') ;  % for eg ML19a
      t = cell2table(uitbl.Data, 'VariableNames', uitblColumnNameSanitized) ;

      FLDS_MARKER = {'Marker' 'MarkerSize' 'LineWidth'} ;
      tLine = t(:,FLDS_MARKER) ;
      sLine = table2struct(tLine) ;

      FLDS_TEXT = {'Show_Text_Label', 'Label_Font_Size' 'Label_Font_Angle'} ;
      tTxt = t(:,FLDS_TEXT) ;
      tTxt.Properties.VariableNames = {'Visible' 'FontSize' 'FontAngle'} ;
      tTxt.Visible = arrayfun(@onIff, tTxt.Visible, 'uni', 0) ;
      sTxt = table2struct(tTxt) ;

      txtOffset = t{:,'Label_Offset'} ;

      s = struct(...
        'landmarkSetType', num2cell(enumeration('LandmarkSetType')), ...
        'MarkerProps', num2cell(sLine), ...
        'TextProps', num2cell(sTxt), ...
        'TextOffset', num2cell(txtOffset) ...
        ) ;
    end  % function

    %%%%%%%%%%%%
    % SKELETON %
    %%%%%%%%%%%%

    function skelControlsSet_(obj, s)
      s1 = s(1).SkeletonProps ;
      obj.pbSkeletonColor_.BackgroundColor = s1.Color ;
      obj.sldSkeletonLineWidth_.Value = log2(s1.LineWidth) ;
    end  % function

    function s = skelControlsGet_(obj)
      s0 = struct() ;
      s0.Color = obj.pbSkeletonColor_.BackgroundColor ;
      s0.LineWidth = 2^obj.sldSkeletonLineWidth_.Value ;
      s = struct(...
        'landmarkSetType', num2cell(enumeration('LandmarkSetType')), ...
        'SkeletonProps', s0) ;
    end  % function

    %%%%%%%%%%%%%%%%%%
    % APPLY/DONE/ETC %
    %%%%%%%%%%%%%%%%%%

    function saveState_(obj)
      % Compute the set of changed specs, storing it in obj.saved_.
      tfApplyAll = obj.cbApplyAll_.Value ;
      iCS = obj.pumShowing_.Value ;
      if tfApplyAll
        colorSpecs = obj.colorSpecs_ ;
        for i = 1:numel(colorSpecs)
          if i == iCS
            continue ;
          end
          colorSpecs(i).copyColorState(colorSpecs(iCS)) ;
        end
        colorSpecs0 = obj.colorSpecs0_ ;
      else
        colorSpecs = obj.colorSpecs_(iCS) ;
        colorSpecs0 = obj.colorSpecs0_(iCS) ;
      end
      colorSpecs.setManualColorsToColormapIfNec() ;
      sPropsMrkr = obj.markerControlsGet_() ;
      sPropsSkel = obj.skelControlsGet_() ;

      tfclrchanged = ~arrayfun(@isequal, colorSpecs, colorSpecs0) ;
      % handles.sPropsMrkr0 might have properties that are not visible/editable
      % in the UI, hence the structoverlay comparison.
      tfmkrchanged = ~arrayfun(@(x,y)isequaln(x,structoverlay(x,y)), ...
        obj.sPropsMrkr0_, sPropsMrkr) ;
      tfskelchanged = ~arrayfun(@(x,y)isequaln(x,structoverlay(x,y)), ...
        obj.sPropsSkel0_, sPropsSkel) ;

      obj.saved_ = struct(...
        'colorSpecs', colorSpecs(tfclrchanged), ...
        'markerSpecs', sPropsMrkr(tfmkrchanged), ...
        'skeletonSpecs', sPropsSkel(tfskelchanged) ...
        ) ;
      % Note any field of obj.saved_ could be empty.
    end  % function

    function applyActuated_(obj)
      obj.saveState_() ;
      saved = obj.saved_ ;
      obj.applyCbkFcn_(saved.colorSpecs, saved.markerSpecs, saved.skeletonSpecs) ;
    end  % function

    function doneActuated_(obj)
      % Apply happens live on every edit, so Done simply closes the dialog.
      obj.closeRequested_() ;
    end  % function

    function tblCellEditActuated_(obj)
      obj.applyActuated_() ;
    end  % function

    function sldSkeletonLineWidthActuated_(obj)
      obj.applyActuated_() ;
    end  % function

    function pbSkeletonColorActuated_(obj)
      c0 = obj.pbSkeletonColor_.BackgroundColor ;
      clr = uisetcolor(c0) ;
      % uisetcolor returns the empty array if the user cancels the dialog; in
      % that case leave the skeleton color unchanged and do not re-apply.
      if isempty(clr)
        return ;
      end
      obj.pbSkeletonColor_.BackgroundColor = clr ;
      obj.applyActuated_() ;
    end  % function

    function closeRequested_(obj)
      % Close the dialog (non-blocking; live-applied changes remain in effect).
      delete(obj) ;
    end  % function

  end  % methods
end  % classdef
