classdef NavPrefsController < handle
  % Controller for the "Navigation Preferences" dialog (Ctrl-arrow frame
  % increment, playback speed and loop radius, and the Shift-arrow seek mode
  % with its timeline-statistic threshold).
  %
  % This replaces the legacy GUIDE app NavPrefsNew.m / NavPrefsNewMat.m.  The
  % figure is built programmatically in createGui_() (layout lifted from
  % GUIDE's export), the widget handles live as instance properties (no more
  % guidata reach-throughs), and the dialog is modal but non-blocking (no
  % uiwait): the constructor returns immediately, and Apply writes the edited
  % values to the Labeler and closes the dialog, while Cancel just closes it.

  properties (Transient)
    hFig  % the dialog figure
    parent_  % a LabelerController
    labeler_  % a Labeler

    % State (formerly stored in pumShiftArrow's UserData)
    shiftArrowModes_  % [n x 1] ShiftArrowMovieNavMode, one per entry of pumShiftArrow_

    % Widget handles, formerly reached via guidata(obj.hFig).
    etFrameSkip_
    etPlaybackSpeed_
    etPlaybackLoopDiameter_
    pumShiftArrow_
    txTimelineProp_  % name of the current timeline statistic, thresholded by the NEXTTIMELINETHRESH mode
    pumShiftArrowTimelineThreshCmp_
    etShiftArrowTimelineThresh_
    pbApply_
    pbCancel_
  end  % properties

  methods
    function obj = NavPrefsController(parent, labeler)
      % Build the dialog and initialize its controls from the Labeler.
      obj.parent_ = parent ;
      obj.labeler_ = labeler ;

      obj.createGui_() ;
      obj.initControlsFromModel_() ;
      obj.updateTimelineStatComparisonEnable_() ;

      obj.hFig.Visible = 'on' ;
    end  % function

    function delete(obj)
      % Tear down the figure.
      deleteValidGraphicsHandles(obj.hFig) ;
      obj.hFig = [] ;
    end  % function

    function createGui_(obj)
      % Build the dialog figure and its widgets programmatically, storing the
      % widget handles as instance properties.  Layout lifted from GUIDE's
      % export of NavPrefs.fig.  The figure is created invisible; the
      % constructor shows it once the controls are populated.
      obj.hFig = figure(...
        'Units', 'pixels', ...
        'Position', [2916 915 551 248], ...
        'Visible', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'DockControls', 'off', ...
        'NumberTitle', 'off', ...
        'IntegerHandle', 'off', ...
        'Name', 'Navigation Preferences', ...
        'WindowStyle', 'modal', ...
        'Resize', 'off', ...
        'Tag', 'figure_navprefs', ...
        'CloseRequestFcn', @(s,e)(obj.closeRequested_())) ;

      % Playback speed
      uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Playback speed (fps):', ...
        'Position', [14 198 200 30], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Tag', 'text4') ;

      obj.etPlaybackSpeed_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'edit', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'left', ...
        'String', '', ...
        'Position', [219 204 90 30], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 13.3333333333333, ...
        'Tooltip', 'Frames per second during playback', ...
        'Tag', 'etPlaybackSpeed', ...
        'Callback', @(s,e)(obj.etPlaybackSpeedActuated_())) ;

      % Playback loop radius
      uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Playback loop radius:', ...
        'Position', [14 165 200 30], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Tag', 'text6') ;

      obj.etPlaybackLoopDiameter_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'edit', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'left', ...
        'String', '', ...
        'Position', [219 171 90 30], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 13.3333333333333, ...
        'Tooltip', 'Number of frames shown during segment/loop playback', ...
        'Tag', 'etPlaybackLoopDiameter', ...
        'Callback', @(s,e)(obj.etPlaybackLoopDiameterActuated_())) ;

      % Ctrl-arrow frame increment
      uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'right', ...
        'String', {'Ctrl-left/right ' ; 'frame increment:'}, ...
        'Position', [14 111 200 45], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Tag', 'text2') ;

      obj.etFrameSkip_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'edit', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'left', ...
        'String', '', ...
        'Position', [219 127 90 30], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 13.3333333333333, ...
        'Tooltip', 'Number of frames to skip when using up/down arrows', ...
        'Tag', 'etFrameSkip', ...
        'Callback', @(s,e)(obj.etFrameSkipActuated_())) ;

      % Shift-arrow seek mode
      uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'right', ...
        'String', 'Shift-left/right seeks:', ...
        'Position', [14 81 200 30], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Tag', 'text3') ;

      obj.pumShiftArrow_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'popupmenu', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'String', {'Pop-up Menu'}, ...
        'Position', [219 89 317 30], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 13.3333333333333, ...
        'Tag', 'pumShiftArrow', ...
        'Callback', @(s,e)(obj.pumShiftArrowActuated_())) ;

      % Timeline-statistic threshold row (enabled only for the
      % NEXTTIMELINETHRESH seek mode)
      obj.txTimelineProp_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'right', ...
        'String', '', ...
        'Position', [14 48 200 30], ...
        'FontSize', 16, ...
        'FontAngle', 'italic', ...
        'FontWeight', 'bold', ...
        'Tag', 'txTimelineProp') ;

      obj.pumShiftArrowTimelineThreshCmp_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'popupmenu', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'String', {'>' ; '<' ; '>=' ; '<='}, ...
        'Position', [221 48 48 30], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 16, ...
        'Tooltip', 'Comparison operator for timeline statistic', ...
        'Tag', 'pumShiftArrowTimelineThreshCmp') ;

      obj.etShiftArrowTimelineThresh_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'edit', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'HorizontalAlignment', 'left', ...
        'String', '', ...
        'Position', [274 50 90 30], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 13.3333333333333, ...
        'Tooltip', 'Threshold for timeline statistics during seek', ...
        'Tag', 'etShiftArrowTimelineThresh', ...
        'Callback', @(s,e)(obj.etShiftArrowTimelineThreshActuated_())) ;

      % Apply / Cancel
      obj.pbApply_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'String', 'Apply', ...
        'Position', [174 3 100 36], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Tag', 'pbApply', ...
        'Callback', @(s,e)(obj.applyActuated_())) ;

      obj.pbCancel_ = uicontrol(...
        'Parent', obj.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'pixels', ...
        'FontUnits', 'pixels', ...
        'String', 'Cancel', ...
        'Position', [277 3 100 36], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Tag', 'pbCancel', ...
        'Callback', @(s,e)(obj.cancelActuated_())) ;

      % Center on the main APT window.
      if ~isempty(obj.parent_)
        mainFigurePosition = obj.parent_.mainFigurePixelPosition() ;
        centerOnOtherFigureGivenPositionBang(obj.hFig, mainFigurePosition) ;
      end
    end  % function

    function initControlsFromModel_(obj)
      % Populate the controls from the Labeler's current navigation
      % preferences (once, at open).
      labeler = obj.labeler_ ;

      obj.etFrameSkip_.String = num2str(labeler.movieFrameStepBig) ;
      obj.etPlaybackSpeed_.String = num2str(labeler.moviePlayFPS) ;
      obj.etPlaybackLoopDiameter_.String = num2str(labeler.moviePlaySegRadius) ;

      shiftArrowModes = enumeration('ShiftArrowMovieNavMode') ;
      obj.shiftArrowModes_ = shiftArrowModes ;
      pum = obj.pumShiftArrow_ ;
      pum.String = arrayfun(@(x)(x.prettyStr), shiftArrowModes, 'UniformOutput', false) ;
      pum.Value = find(labeler.movieShiftArrowNavMode == shiftArrowModes) ;

      obj.etShiftArrowTimelineThresh_.String = num2str(labeler.movieShiftArrowNavModeThresh) ;
      pum = obj.pumShiftArrowTimelineThreshCmp_ ;
      idx = find(strcmp(pum.String, labeler.movieShiftArrowNavModeThreshCmp)) ;
      assert(isscalar(idx)) ;
      pum.Value = idx ;

      infoTimelineModel = labeler.infoTimelineModel ;
      [~, timelineProp] = infoTimelineModel.getCurPropSmart() ;
      obj.txTimelineProp_.String = timelineProp.name ;
    end  % function

    function updateTimelineStatComparisonEnable_(obj)
      % Enable the timeline-statistic threshold row iff the selected seek
      % mode is NEXTTIMELINETHRESH.
      seekMode = obj.selectedShiftArrowMode_() ;
      isTimelineThresh = (seekMode == ShiftArrowMovieNavMode.NEXTTIMELINETHRESH) ;
      onoff = onIff(isTimelineThresh) ;

      obj.txTimelineProp_.Enable = onoff ;
      obj.pumShiftArrowTimelineThreshCmp_.Enable = onoff ;
      obj.etShiftArrowTimelineThresh_.Enable = onoff ;
    end  % function

    function seekMode = selectedShiftArrowMode_(obj)
      % The ShiftArrowMovieNavMode currently selected in pumShiftArrow_.
      seekMode = obj.shiftArrowModes_(obj.pumShiftArrow_.Value) ;
    end  % function

    %%%%%%%%%%%%%%%%%%%%%%%%%%
    % EDIT-FIELD VALIDATION  %
    %%%%%%%%%%%%%%%%%%%%%%%%%%

    function etFrameSkipActuated_(obj)
      % Revert to the model value if the entry is not a number.
      val = str2double(obj.etFrameSkip_.String) ;
      if isnan(val)
        obj.etFrameSkip_.String = num2str(obj.labeler_.movieFrameStepBig) ;
      end
    end  % function

    function etPlaybackSpeedActuated_(obj)
      % Revert to the model value if the entry is not a positive number.
      val = str2double(obj.etPlaybackSpeed_.String) ;
      if isnan(val) || val <= 0
        obj.etPlaybackSpeed_.String = num2str(obj.labeler_.moviePlayFPS) ;
      end
    end  % function

    function etPlaybackLoopDiameterActuated_(obj)
      % Revert to the model value if the entry is not a positive number.
      val = str2double(obj.etPlaybackLoopDiameter_.String) ;
      if isnan(val) || val <= 0
        obj.etPlaybackLoopDiameter_.String = num2str(obj.labeler_.moviePlaySegRadius) ;
      end
    end  % function

    function etShiftArrowTimelineThreshActuated_(obj)
      % Revert to the model value if the entry is not a number.
      val = str2double(obj.etShiftArrowTimelineThresh_.String) ;
      if isnan(val)
        obj.etShiftArrowTimelineThresh_.String = num2str(obj.labeler_.movieShiftArrowNavModeThresh) ;
      end
    end  % function

    function pumShiftArrowActuated_(obj)
      % The seek mode changed; the threshold row applies only to one mode.
      obj.updateTimelineStatComparisonEnable_() ;
    end  % function

    %%%%%%%%%%%%%%%%%%%%
    % APPLY/CANCEL/ETC %
    %%%%%%%%%%%%%%%%%%%%

    function applyActuated_(obj)
      % Write the edited preferences to the Labeler, then close the dialog.
      obj.writePreferencesToModel_() ;
      obj.closeRequested_() ;
    end  % function

    function writePreferencesToModel_(obj)
      % Write the edited preferences to the Labeler.
      obj.labeler_.movieFrameStepBig = str2double(obj.etFrameSkip_.String) ;
      obj.labeler_.moviePlayFPS = str2double(obj.etPlaybackSpeed_.String) ;
      obj.labeler_.moviePlaySegRadius = str2double(obj.etPlaybackLoopDiameter_.String) ;
      seekMode = obj.selectedShiftArrowMode_() ;
      obj.labeler_.movieShiftArrowNavMode = seekMode ;

      if seekMode == ShiftArrowMovieNavMode.NEXTTIMELINETHRESH
        pum = obj.pumShiftArrowTimelineThreshCmp_ ;
        cmp = pum.String{pum.Value} ;
        thresh = str2double(obj.etShiftArrowTimelineThresh_.String) ;
        obj.labeler_.setMovieShiftArrowNavModeThresh(thresh) ;
        obj.labeler_.movieShiftArrowNavModeThreshCmp = cmp ;
      end
    end  % function

    function cancelActuated_(obj)
      % Discard the edits and close the dialog.
      obj.closeRequested_() ;
    end  % function

    function closeRequested_(obj)
      % Close the dialog (non-blocking; nothing is applied on close).
      delete(obj) ;
    end  % function

  end  % methods
end  % classdef
