name: apt-2025-04
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch-gpu>=2.1
  - tensorflow-gpu
  - mmdet  
  - mmcv>=2.0,<2.2
  - scikit-image
  - hdf5storage
  - keras-applications
  - easydict
  - pandas
  - ruamel.yaml
  - shapely
  - openvino
  - tf_slim
  - torchvision
  # Start of pip stuff dependencies
  - aenum
  - dill
  - json_tricks
  - multiprocess
  - prettytable 
  - wcwidth 
  - protobuf  # one of the pip things seemingly needs protobuf 3
  - onnx
  # End of pip stuff dependencies
  - pip
  - pip:
      # - chumpy
      - xtcocotools
      - mmpose
      - mmdeploy
  