function [stg1net, stg2net] = get_custom_two_stage_tracker_nets_ui(mainFigure, stg1nets, stg2nets)
  stg1net = [];
  stg2net = [];
  stg1nets_str = cell(1, numel(stg1nets)) ;
  for ndx = 1:numel(stg1nets)
    stg1nets_str{ndx} = stg1nets(ndx).displayString;
  end
  stg2nets_str = cell(1, numel(stg2nets)) ;
  for ndx = 1:numel(stg2nets)
    stg2nets_str{ndx} = stg2nets(ndx).displayString;
  end
  fig = uifigure('Name','Custom Top-Down Tracker',...
                 'Units','pixels', ...
                 'Position',[100,100,500,300], ...
                 'WindowStyle', 'modal', ...
                 'Resize', 'off', ...
                 'Visible','off', ...
                 'CloseRequestFcn', @cancel_callback) ;
  centerOnParentFigure(fig,mainFigure);
  s1_list = uilistbox(fig,...
                      'Position',[10 60 235 200],...
                      'Items',stg1nets_str);
  s2_list = uilistbox(fig,...
                      'Position',[255 60 235 200],...
                      'Items',stg2nets_str);
  uilabel(fig,...
          'Text','Network for Stage 1 (Detection)',...
          'Position',[10 265 235 20]);
  uilabel(fig,...
          'Text','Network for Stage 2 (Pose)',...
          'Position',[255 265 235 20]);
  pb_ok = uibutton(fig,'push',...
                   'Position',[50 10 150 40],...
                   'Text','OK', ....
                   'ButtonPushedFcn',@ok_callback);  %#ok<NASGU>
  pb_cancel = uibutton(fig,'push',...
                       'Position',[300 10 150 40],...
                       'Text','Cancel', ....
                       'ButtonPushedFcn',@cancel_callback);  %#ok<NASGU>
  fig.Visible = 'on' ;
  uiwait(fig);

  function cancel_callback(src,event)  %#ok<INUSD>
    stg1net = [];
    stg2net = [];
    delete(fig);
  end

  function ok_callback(src,event)  %#ok<INUSD>
    stg1net_ndx = find(strcmp(s1_list.Items,s1_list.Value));
    stg1net = stg1nets(stg1net_ndx);  %#ok<FNDSB>
    stg2net_ndx = find(strcmp(s2_list.Items,s2_list.Value));
    stg2net = stg2nets(stg2net_ndx);  %#ok<FNDSB>
    delete(fig);
  end

end  % function get_custom_two_stage_tracker_nets_ui()
