name: APT
channels:
  - defaults
  - pytorch
  - intel
  - anaconda
  - conda-forge
dependencies:
  - conda
  - python=3.7.7
  - conda-build
  - pyyaml
  - ipython
  - numpy=1.20
  - torchvision=0.7.0
  - pytorch=1.6.0
  - cudatoolkit=10.1
  - tensorflow==2.3.0
  - pip=22
  - mkl_fft
  - mkl_random
  - mkl-service
  - pip:
    - absl-py
    - addict
    - astunparse
    - attrs
    - av
    - backcall
    - beautifulsoup4
    - cachetools
    - certifi
    - cffi
    - chardet
    - chumpy
    - click
    - clize
#    - conda==4.8.3
#    - conda-build==3.18.11
#    - conda-package-handling==1.7.0
    - crc32c
    - cryptography
    - cycler
    - Cython
    - decorator
    - docutils
    - easydict
    - filelock
    - flake8
    - flake8-import-order
    - func-timeout
    - future
    - gast
    - gdown
    - glob2
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py==2.10.0
    - hdf5storage
    - idna
    - imageio
    - imgaug
    - importlib-metadata
    - iniconfig
    - ipython
    - ipython-genutils
    - jedi
    - Jinja2
    - joblib
    - json-tricks
    - Keras==2.2.4
    - Keras-Applications==1.0.8
    - Keras-Preprocessing
    - kiwisolver
    - libarchive-c
    - llvmlite
    - Markdown
    - MarkupSafe
    - matplotlib
    - mccabe
#    - mmcv-full==1.3.8
#    - mmcv-full==1.3.3 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
    - git+https://github.com/open-mmlab/mmcv.git@e728608ac90c0a6e4046082e4d0a9996e2961f44
    - motmetrics
    - munkres
    - networkx
    - numba
    - numpy
    - oauthlib
    - od
    - olefile
    - onnx
    - onnxruntime
    - opencv-python
    - opt-einsum
    - ordereddict
    - packaging
    - pandas
    - parso
    - patsy
    - pexpect
    - pickle5
    - pickleshare
    - Pillow
    - PIMS
    - pkginfo
    - pluggy
    - git+https://github.com/svenkreiss/poseval.git
    - progressbar
    - promise
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - py
    - py-cpuinfo
    - pyasn1
    - pyasn1-modules
    - pycocotools
    - pycodestyle
    - pycosat
    - pycparser
    - pyflakes
    - Pygments
    - pyOpenSSL
    - pyparsing
    - PySocks
    - pytest
    - pytest-benchmark
    - python-dateutil
    - pytz
    - PyWavelets
    - PyYAML
    - requests
    - requests-oauthlib
    - rsa
    - ruamel-yaml
    - ruamel.yaml.clib
    - scikit-image
    - scikit-learn
    - scipy==1.4.1
    - Shapely
    - sigtools
    - six
    - sklearn
    - slicerator
    - smplx
    - snakeviz
    - soupsieve
    - statsmodels
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
#    - tensorflow==2.3.0
    - tensorflow-estimator
    - termcolor
    - terminaltables
    - tf-slim==1.1.0
    - tfrecord
    - threadpoolctl
    - tifffile
    - toml
    - torch==1.6.0
    - torchvision==0.7.0
    - tornado
    - tqdm
    - traitlets
    - typing-extensions
    - urllib3
    - wcwidth
    - Werkzeug
    - wrapt
    - xmltodict
    - xtcocotools
#    - https://files.pythonhosted.org/packages/84/93/26a2e38034f5cee86403525118f2cac68bb2aafc4797bcebea0c056611cb/xtcocotools-1.7-cp37-cp37m-manylinux1_x86_64.whl
    - yapf
    - zipp
