#FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
FROM tensorflow/tensorflow:1.6.0-devel-gpu
LABEL maintainer "kabram@janelia.hhmi.org"

#2.7
ENV PYTHON_VERSION 2.7

# Install all dependencies for OpenCV 3.2
RUN apt-get -y update && apt-get -y install python$PYTHON_VERSION-dev wget unzip \
    build-essential cmake git pkg-config libatlas-base-dev gfortran \
    libjasper-dev libgtk2.0-dev libavcodec-dev libavformat-dev \
    libswscale-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libv4l-dev \
    && wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py && pip install numpy\
    && wget https://github.com/opencv/opencv/archive/2.4.13.6.zip -O opencv3.zip \
    && unzip -q opencv3.zip && mv opencv-2.4.13.6 /opencv && rm opencv3.zip \

    # prepare build
    && mkdir /opencv/build && cd /opencv/build \
    && cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D BUILD_PYTHON_SUPPORT=ON \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_EXAMPLES=OFF \
      -D WITH_IPP=OFF \
      -D WITH_FFMPEG=ON \
      -D WITH_V4L=ON \
	  -D WITH_CUDA=OFF .. \

    # install
    && cd /opencv/build && make -j$(nproc) && make install && ldconfig \

    #clean
    && apt-get -y remove build-essential cmake git pkg-config libatlas-base-dev gfortran \
    libjasper-dev libgtk2.0-dev libavcodec-dev libavformat-dev \
    libswscale-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libv4l-dev \
    && apt-get clean \
	&& cd / \
    && rm -rf /opencv /opencv_contrib /var/lib/apt/lists/* \

    && pip install ipython imageio Keras==2.2.4 h5py enum EasyDict scipy future scikit-image hdf5storage \ 
    &&  python -mpip install -U pip \ 
    &&  python -mpip install -U matplotlib \ 
    &&  apt-get update  \ 
    &&  apt-get install -y vim \ 
    &&  apt-get install -y python-tk \ 
    &&  apt-get install -y software-properties-common \ 
    &&  add-apt-repository ppa:jonathonf/ffmpeg-3 \ 
    &&  apt-get update \ 
    &&  apt-get install -y ffmpeg libav-tools x264 x265  



# Define default command.
CMD ["bash"]
