function [icat,cats] = shmovieCat(m)
tf = [...
        ~isempty(regexp(m,'pre2016_trainingData_kineFormat_blindToErrors','once')) ... 
        ~isempty(regexp(m,'2016_trainingData_blindToErrors','once')) ... 
        ~isempty(regexp(m,'18012017_trainingData_errorTargetted','once')) ...
        ~isempty(regexp(m,'Nov2017_trainingData','once')) ...
        ~isempty(regexp(m,'headAndBody_NOTerrorTargetted','once')) ... 
        ~isempty(regexp(m,'bodyAxis_APT_projects','once')) ];
icat = find(tf);
if isscalar(icat)
  % none
elseif isequal(icat,[3 5])
  icat = 5; 
end

CATSTRS = {'kine' '2016' '2017jan' '2017nov' 'HaB' 'bAxis'};
cats = CATSTRS{icat};