function codestr = codeGenBsubGeneral(basecmd,varargin)

[nslots,gpuqueue,outfile,additionalargs] = ...
  myparse(varargin,...
          'nslots',1,...
          'gpuqueue',DLBackEndClass.default_jrcgpuqueue,...
          'outfile','/dev/null', ...
          'additionalargs', '');
codestr = sprintf('bsub -n %d -gpu "num=1" -q %s -o "%s" -R"affinity[core(1)]" %s %s',...
                  nslots,gpuqueue,outfile,additionalargs,basecmd);      

end
