function [startFrameFromBoutIndex, ...
          endFrameFromBoutIndex, ...
          extremalConfTrackletFrameIndexFromBoutIndex, ...
          trackletIndexFromBoutIndex, ...
          targetIndexFromBoutIndex, ...
          extremalConfFromBoutIndex] = ...
    collectBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                  trackletIndexFromTrackletFrameIndex, ...
                                  targetIndexFromTrackletFrameIndex, ...
                                  minConfFromTrackletFrameIndex, ...
                                  maxConfFromTrackletFrameIndex, ...
                                  threshold, ...
                                  isConfidenceLackThereof)
% Gather all bout outputs for one tracklet from per-tracklet confidence data.

[startFrameFromBoutIndex, ...
  endFrameFromBoutIndex, ...
 extremalConfTrackletFrameIndexFromBoutIndex, ...
 extremalConfFromBoutIndex] = ...
  confidenceBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                   minConfFromTrackletFrameIndex, ...
                                   maxConfFromTrackletFrameIndex, ...
                                   threshold, ...
                                   isConfidenceLackThereof) ;

trackletBoutCount = numel(startFrameFromBoutIndex) ;
if trackletBoutCount == 0
  trackletIndexFromBoutIndex = zeros(0, 1) ;
  targetIndexFromBoutIndex = zeros(0, 1) ;
else
  trackletIndex = trackletIndexFromTrackletFrameIndex(1) ;  % scalar
  targetIndex = targetIndexFromTrackletFrameIndex(1) ;  % scalar
  trackletIndexFromBoutIndex = repmat(trackletIndex, trackletBoutCount, 1) ;
  targetIndexFromBoutIndex = repmat(targetIndex, trackletBoutCount, 1) ;
end

end  % function
