function [startFrameFromBoutIndex, ...
          endFrameFromBoutIndex, ...
          extremalConfTrackletFrameIndexFromBoutIndex, ...
          trackletIndexFromBoutIndex, ...
          targetIndexFromBoutIndex, ...
          extremalConfFromBoutIndex] = ...
    collectBoutsForSingleTracklet(trackletIndex, ...
                                  frameIndexFromPairIndex, ...
                                  trackletIndexFromPairIndex, ...
                                  targetIndexFromPairIndex, ...
                                  minConfFromPairIndex, ...
                                  maxConfFromPairIndex, ...
                                  threshold, ...
                                  isConfidenceLackThereof)
% Gather all bout outputs for one tracklet from flattened confidence data.
isThisTrackletFromPairIndex = (trackletIndexFromPairIndex == trackletIndex) ;
frameIndexFromTrackletFrameIndex = frameIndexFromPairIndex(isThisTrackletFromPairIndex) ;
minConfFromTrackletFrameIndex = minConfFromPairIndex(isThisTrackletFromPairIndex) ;
maxConfFromTrackletFrameIndex = maxConfFromPairIndex(isThisTrackletFromPairIndex) ;
targetIndex = targetIndexFromPairIndex(find(isThisTrackletFromPairIndex, 1)) ;  % scalar

[startFrameFromBoutIndex, ...
  endFrameFromBoutIndex, ...
 extremalConfTrackletFrameIndexFromBoutIndex, ...
 extremalConfFromBoutIndex] = ...
  confidenceBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                   minConfFromTrackletFrameIndex, ...
                                   maxConfFromTrackletFrameIndex, ...
                                   threshold, ...
                                   isConfidenceLackThereof) ;

trackletBoutCount = numel(startFrameFromBoutIndex) ;
trackletIndexFromBoutIndex = repmat(trackletIndex, trackletBoutCount, 1) ;
targetIndexFromBoutIndex = repmat(targetIndex, trackletBoutCount, 1) ;

end  % function
