function [firstFrameIndexFromTrackletBoutIndex, ...
          lastFrameIndexFromTrackletBoutIndex, ...
          extremalConfFrameIndexFromTrackletBoutIndex, ...
          trackletIndexFromTrackletBoutIndex, ...
          targetIndexFromTrackletBoutIndex, ...
          extremalConfFromTrackletBoutIndex] = ...
    collectBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                  trackletIndex, ...
                                  targetIndex, ...
                                  minConfFromTrackletFrameIndex, ...
                                  maxConfFromTrackletFrameIndex, ...
                                  threshold)
% Gather all bout outputs for one tracklet from per-tracklet confidence data.

[firstFrameIndexFromTrackletBoutIndex, ...
 lastFrameIndexFromTrackletBoutIndex, ...
 extremalConfFrameIndexFromTrackletBoutIndex, ...
 extremalConfFromTrackletBoutIndex] = ...
  confidenceBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                   minConfFromTrackletFrameIndex, ...
                                   maxConfFromTrackletFrameIndex, ...
                                   threshold) ;

trackletBoutCount = numel(firstFrameIndexFromTrackletBoutIndex) ;
if trackletBoutCount == 0
  trackletIndexFromTrackletBoutIndex = zeros(0, 1) ;
  targetIndexFromTrackletBoutIndex = zeros(0, 1) ;
else
  trackletIndexFromTrackletBoutIndex = repmat(trackletIndex, trackletBoutCount, 1) ;
  targetIndexFromTrackletBoutIndex = repmat(targetIndex, trackletBoutCount, 1) ;
end

end  % function
