function [firstFrameIndexFromTrackletBoutIndex, ...
          lastFrameIndexFromTrackletBoutIndex, ...
          extremalInterestFrameIndexFromTrackletBoutIndex, ...
          trackletIndexFromTrackletBoutIndex, ...
          targetIndexFromTrackletBoutIndex, ...
          extremalInterestFromTrackletBoutIndex] = ...
    collectInterestBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                                 trackletIndex, ...
                                                 targetIndex, ...
                                                 interestFromTrackletFrameIndex, ...
                                                 threshold)
% Gather all bout outputs for one tracklet from per-tracklet
% interest data.

[firstFrameIndexFromTrackletBoutIndex, ...
 lastFrameIndexFromTrackletBoutIndex, ...
 extremalInterestFrameIndexFromTrackletBoutIndex, ...
 extremalInterestFromTrackletBoutIndex] = ...
  interestBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                        interestFromTrackletFrameIndex, ...
                                        threshold) ;

trackletBoutCount = numel(firstFrameIndexFromTrackletBoutIndex) ;
if trackletBoutCount == 0
  trackletIndexFromTrackletBoutIndex = zeros(0, 1) ;
  targetIndexFromTrackletBoutIndex = zeros(0, 1) ;
else
  trackletIndexFromTrackletBoutIndex = repmat(trackletIndex, trackletBoutCount, 1) ;
  targetIndexFromTrackletBoutIndex = repmat(targetIndex, trackletBoutCount, 1) ;
end

end  % function
