function [firstFrameIndexFromSortedBoutIndex, lastFrameIndexFromSortedBoutIndex, extremalConfFrameIndexFromSortedBoutIndex, ...
          trackletIndexFromSortedBoutIndex, targetIndexFromSortedBoutIndex, extremalConfFromSortedBoutIndex, ...
          minConf, maxConf, ...
          absoluteThreshold] = ...
  confidenceBoutsFromTrkFile(trkFile, naiveQuantileThreshold, isConfidenceLackThereof)
% Find bouts of consecutive frames whose confidence is above a threshold.
%
% A bout is a maximal contiguous run of consecutive frames (within a single
% tracklet) where confidence stays below (or above, in lack-thereof mode)
% the quantile-derived threshold.  Each bout is represented by the frame
% achieving the extreme confidence within the run.
%
% The quantile threshold is interpreted on per-frame minima in the normal
% mode and on per-frame maxima in lack-thereof mode.
%
% Returns empty column vectors and NaN extremes when there are no bouts.

% Gather per-frame confidence data from all tracklets.
trackletCount = trkFile.ntracklets ;
trackletIndices = (1 : trackletCount)' ;
[frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
 trackletIndexFromTrackletIndex, ...
 targetIndexFromTrackletIndex, ...
 minConfFromTrackletFrameIndexFromTrackletIndex, ...
 maxConfFromTrackletFrameIndexFromTrackletIndex] = ...
  arrayfun(@(trackletIndex) collectConfidenceDataForSingleTracklet(trkFile, trackletIndex), ...
           trackletIndices, ...
           'UniformOutput', false) ;

% Concatenate all the *FromTrackletIndex cell arrays together, thus
% collecting all valid (frame, tracklet) pairs into flattened vectors.
minConfFromPairIndex = vertcat(minConfFromTrackletFrameIndexFromTrackletIndex{:}) ;
maxConfFromPairIndex = vertcat(maxConfFromTrackletFrameIndexFromTrackletIndex{:}) ;

% Do an early return if there are no pairs
if isempty(minConfFromPairIndex)
  firstFrameIndexFromSortedBoutIndex = zeros(0, 1) ;
  lastFrameIndexFromSortedBoutIndex = zeros(0, 1) ;
  extremalConfFrameIndexFromSortedBoutIndex = zeros(0, 1) ;
  trackletIndexFromSortedBoutIndex = zeros(0, 1) ;
  targetIndexFromSortedBoutIndex = zeros(0, 1) ;
  extremalConfFromSortedBoutIndex = zeros(0, 1) ;
  minConf = nan ;
  maxConf = nan ;
  absoluteThreshold = nan ;
  return
end

% Record overall extremes before filtering.
minConf = min(minConfFromPairIndex) ;
maxConf = max(maxConfFromPairIndex) ;

% Compute the quantile threshold.  The convention is that a higher quantile
% threshold should result in fewer points 'passing through the filter'.  If
% "confidence" is actually lack-of-confidence (i.e. uncertainty), then we
% can just use naiveQuantileThreshold and this works with quantile().  But
% if "confidence" really is confidence, we need to use
% 1-naiveQuantileThreshold when we call quantile() to get the desired
% semantics.
quantileThreshold = fif(isConfidenceLackThereof, naiveQuantileThreshold, 1-naiveQuantileThreshold) ;
confFromPairIndex = fif(isConfidenceLackThereof, maxConfFromPairIndex, minConfFromPairIndex) ;
absoluteThreshold = quantile(confFromPairIndex, quantileThreshold) ;

% Build bouts: contiguous runs of consecutive frames (within a single
% tracklet) that pass the confidence threshold.
[firstFrameIndexFromTrackletBoutIndexFromTrackletIndex, ...
 lastFrameIndexFromTrackletBoutIndexFromTrackletIndex, ...
 extremalFrameIndexFromTrackletBoutIndexFromTrackletIndex, ...
 trackletIndexFromTrackletBoutIndexFromTrackletIndex, ...
 targetIndexFromTrackletBoutIndexFromTrackletIndex, ...
 extremalConfFromTrackletBoutIndexFromTrackletIndex] = ...
  cellfun(@(frameIndexFromTrackletFrameIndex, ...
            trackletIndex, ...
            targetIndex, ...
            minConfFromTrackletFrameIndex, ...
            maxConfFromTrackletFrameIndex) ...
            collectBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                          trackletIndex, ...
                                          targetIndex, ...
                                          minConfFromTrackletFrameIndex, ...
                                          maxConfFromTrackletFrameIndex, ...
                                          absoluteThreshold, ...
                                          isConfidenceLackThereof), ...
          frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
          trackletIndexFromTrackletIndex, ...
          targetIndexFromTrackletIndex, ...
          minConfFromTrackletFrameIndexFromTrackletIndex, ...
          maxConfFromTrackletFrameIndexFromTrackletIndex, ...
          'UniformOutput', false) ;

% Concatenate all the *FromTrackletIndex cell arrays together, thus
% collecting all the bouts from all the tracklets.
firstFrameIndexFromBoutIndex = vertcat(firstFrameIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
lastFrameIndexFromBoutIndex = vertcat(lastFrameIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
trackletIndexFromBoutIndex = vertcat(trackletIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
targetIndexFromBoutIndex = vertcat(targetIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
extremalConfFromBoutIndex = vertcat(extremalConfFromTrackletBoutIndexFromTrackletIndex{:}) ;
extremeConfFrameIndexFromBoutIndex = vertcat(extremalFrameIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;

% Sort bouts by extremal confidence.
sortOrder = fif(isConfidenceLackThereof, 'descend', 'ascend') ;
[~, boutIndexFromSortedBoutIndex] = sort(extremalConfFromBoutIndex, sortOrder) ;

% Sort everything else according to the sort order
firstFrameIndexFromSortedBoutIndex = firstFrameIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
lastFrameIndexFromSortedBoutIndex = lastFrameIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
extremalConfFrameIndexFromSortedBoutIndex = extremeConfFrameIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
trackletIndexFromSortedBoutIndex = trackletIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
targetIndexFromSortedBoutIndex = targetIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
extremalConfFromSortedBoutIndex = extremalConfFromBoutIndex(boutIndexFromSortedBoutIndex) ;

end  % function
