function [firstFrameIndexFromSortedBoutIndex, lastFrameIndexFromSortedBoutIndex, extremalConfFrameIndexFromSortedBoutIndex, ...
          trackletIndexFromSortedBoutIndex, targetIndexFromSortedBoutIndex, extremalConfFromSortedBoutIndex, ...
          minConf, maxConf, ...
          absoluteThreshold] = ...
  confidenceBoutsFromTrkFile(trkFile, naiveQuantileThreshold)
% Find bouts of consecutive frames whose minimum landmark confidence falls
% at or below a quantile-derived threshold (i.e. uncertain bouts).
%
% A bout is a maximal contiguous run of consecutive frames (within a single
% tracklet) where the per-frame minimum landmark confidence stays at or
% below the quantile-derived threshold.  Each bout is represented by the
% frame achieving the minimum confidence within the run.
%
% Returns empty column vectors and NaN extremes when there are no bouts.

% Gather per-frame confidence data from all tracklets.
trackletCount = trkFile.ntracklets ;
trackletIndices = (1 : trackletCount)' ;
[frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
 trackletIndexFromTrackletIndex, ...
 targetIndexFromTrackletIndex, ...
 minConfFromTrackletFrameIndexFromTrackletIndex, ...
 maxConfFromTrackletFrameIndexFromTrackletIndex] = ...
  arrayfun(@(trackletIndex) collectConfidenceDataForSingleTracklet(trkFile, trackletIndex), ...
           trackletIndices, ...
           'UniformOutput', false) ;

% Concatenate all the *FromTrackletIndex cell arrays together, thus
% collecting all valid (frame, tracklet) pairs into flattened vectors.
minConfFromPairIndex = vertcat(minConfFromTrackletFrameIndexFromTrackletIndex{:}) ;
maxConfFromPairIndex = vertcat(maxConfFromTrackletFrameIndexFromTrackletIndex{:}) ;

% Do an early return if there are no pairs
if isempty(minConfFromPairIndex)
  firstFrameIndexFromSortedBoutIndex = zeros(0, 1) ;
  lastFrameIndexFromSortedBoutIndex = zeros(0, 1) ;
  extremalConfFrameIndexFromSortedBoutIndex = zeros(0, 1) ;
  trackletIndexFromSortedBoutIndex = zeros(0, 1) ;
  targetIndexFromSortedBoutIndex = zeros(0, 1) ;
  extremalConfFromSortedBoutIndex = zeros(0, 1) ;
  minConf = nan ;
  maxConf = nan ;
  absoluteThreshold = nan ;
  return
end

% Record overall extremes before filtering.
minConf = min(minConfFromPairIndex) ;
maxConf = max(maxConfFromPairIndex) ;

% Compute the quantile threshold.  Higher naiveQuantileThreshold should
% produce fewer (more strictly uncertain) bouts, so we invert to get the
% per-frame-minimum quantile.
quantileThreshold = 1 - naiveQuantileThreshold ;
absoluteThreshold = quantile(minConfFromPairIndex, quantileThreshold) ;

% Build bouts: contiguous runs of consecutive frames (within a single
% tracklet) whose minimum landmark confidence is at or below the threshold.
[firstFrameIndexFromTrackletBoutIndexFromTrackletIndex, ...
 lastFrameIndexFromTrackletBoutIndexFromTrackletIndex, ...
 extremalFrameIndexFromTrackletBoutIndexFromTrackletIndex, ...
 trackletIndexFromTrackletBoutIndexFromTrackletIndex, ...
 targetIndexFromTrackletBoutIndexFromTrackletIndex, ...
 extremalConfFromTrackletBoutIndexFromTrackletIndex] = ...
  cellfun(@(frameIndexFromTrackletFrameIndex, ...
            trackletIndex, ...
            targetIndex, ...
            minConfFromTrackletFrameIndex, ...
            maxConfFromTrackletFrameIndex) ...
            collectBoutsForSingleTracklet(frameIndexFromTrackletFrameIndex, ...
                                          trackletIndex, ...
                                          targetIndex, ...
                                          minConfFromTrackletFrameIndex, ...
                                          maxConfFromTrackletFrameIndex, ...
                                          absoluteThreshold), ...
          frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
          trackletIndexFromTrackletIndex, ...
          targetIndexFromTrackletIndex, ...
          minConfFromTrackletFrameIndexFromTrackletIndex, ...
          maxConfFromTrackletFrameIndexFromTrackletIndex, ...
          'UniformOutput', false) ;

% Concatenate all the *FromTrackletIndex cell arrays together, thus
% collecting all the bouts from all the tracklets.
firstFrameIndexFromBoutIndex = vertcat(firstFrameIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
lastFrameIndexFromBoutIndex = vertcat(lastFrameIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
trackletIndexFromBoutIndex = vertcat(trackletIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
targetIndexFromBoutIndex = vertcat(targetIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;
extremalConfFromBoutIndex = vertcat(extremalConfFromTrackletBoutIndexFromTrackletIndex{:}) ;
extremeConfFrameIndexFromBoutIndex = vertcat(extremalFrameIndexFromTrackletBoutIndexFromTrackletIndex{:}) ;

% Sort bouts by extremal (minimum) confidence: most uncertain first.
[~, boutIndexFromSortedBoutIndex] = sort(extremalConfFromBoutIndex, 'ascend') ;

% Sort everything else according to the sort order
firstFrameIndexFromSortedBoutIndex = firstFrameIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
lastFrameIndexFromSortedBoutIndex = lastFrameIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
extremalConfFrameIndexFromSortedBoutIndex = extremeConfFrameIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
trackletIndexFromSortedBoutIndex = trackletIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
targetIndexFromSortedBoutIndex = targetIndexFromBoutIndex(boutIndexFromSortedBoutIndex) ;
extremalConfFromSortedBoutIndex = extremalConfFromBoutIndex(boutIndexFromSortedBoutIndex) ;

end  % function
