function [firstFrameIndexFromSortedBoutIndex, ...
          lastFrameIndexFromSortedBoutIndex, ...
          minConfFrameIndexFromSortedBoutIndex, ...
          trackletIndexFromSortedBoutIndex, ...
          targetIndexFromSortedBoutIndex, ...
          minConfFromSortedBoutIndex, ...
          absoluteConfidenceThreshold] = ...
  confidenceBoutsFromTrkFile(trkFile, quantileThreshold)
% Find bouts of consecutive frames whose max-landmark interest
% (interest = -confidence) is at or above a quantile-derived threshold
% (i.e. uncertain bouts).
%
% Internally the bout-formation, quantile, and sort calculations all
% happen in the interest domain via interestBoutsFromPerTrackletData: a
% higher interest means a less confident, more uncertain frame.  A bout
% is a maximal contiguous run of consecutive frames (within a single
% tracklet) whose per-frame max-interest stays at or above the
% quantile-derived threshold.  Each bout is represented by the frame
% achieving the maximum interest within the run, and bouts are returned
% in descending order of that max interest (i.e. ascending order of
% per-bout min confidence) -- most uncertain first.
%
% Inputs and outputs are expressed in the confidence domain so callers
% that present results to the user in terms of confidence don't need to
% flip signs.  In particular, quantileThreshold is interpreted in the
% interest domain (so 0.99 keeps the top 1% most-interesting frames),
% and the returned absoluteConfidenceThreshold and minConf* are
% confidence values.
%
% Returns empty column vectors and NaN threshold when there are no bouts.

% Gather per-frame max-interest data from all tracklets.
trackletCount = trkFile.ntracklets ;
trackletIndices = (1 : trackletCount)' ;
[frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
 trackletIndexFromTrackletIndex, ...
 targetIndexFromTrackletIndex, ...
 interestFromTrackletFrameIndexFromTrackletIndex] = ...
  arrayfun(@(trackletIndex) collectInterestDataForSingleTracklet(trkFile, trackletIndex), ...
           trackletIndices, ...
           'UniformOutput', false) ;

% Run the shared bout-formation / quantile / sort pipeline in the
% interest domain.
[firstFrameIndexFromSortedBoutIndex, ...
 lastFrameIndexFromSortedBoutIndex, ...
 maxInterestFrameIndexFromSortedBoutIndex, ...
 trackletIndexFromSortedBoutIndex, ...
 targetIndexFromSortedBoutIndex, ...
 maxInterestFromSortedBoutIndex, ...
 absoluteInterestThreshold] = ...
  interestBoutsFromPerTrackletData(frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
                                   trackletIndexFromTrackletIndex, ...
                                   targetIndexFromTrackletIndex, ...
                                   interestFromTrackletFrameIndexFromTrackletIndex, ...
                                   quantileThreshold) ;

% Translate interest-domain results back to the confidence domain.
minConfFrameIndexFromSortedBoutIndex = maxInterestFrameIndexFromSortedBoutIndex ;
minConfFromSortedBoutIndex = -maxInterestFromSortedBoutIndex ;
absoluteConfidenceThreshold = -absoluteInterestThreshold ;

end  % function
