function [firstFrameIndexFromSortedBoutIndex, ...
          lastFrameIndexFromSortedBoutIndex, ...
          maxDistanceFrameIndexFromSortedBoutIndex, ...
          trackletIndexFromSortedBoutIndex, ...
          targetIndexFromSortedBoutIndex, ...
          maxDistanceFromSortedBoutIndex, ...
          absoluteDistanceThreshold] = ...
  distanceBoutsBetweenTrackers(refTrkFile, ...
                               testTrkFile, ...
                               nframes, ...
                               quantileThreshold, ...
                               centroidMatchThreshold)
% Find bouts of consecutive frames where the per-frame max landmark
% distance between a reference tracker's tracklet and its closest test
% tracker tracklet is at or above a quantile-derived threshold.
%
% For each (frame, ref tracklet) the test tracklet that is closest in
% centroid-to-centroid distance (and within centroidMatchThreshold
% pixels) is taken as the match.  The per-frame interest signal is the
% max over landmarks of the ref-to-test landmark distance.  Frames with
% no matching test tracklet are dropped.  Bouts are returned sorted by
% per-bout max distance, descending (largest disagreement first).
%
% Inputs:
%   refTrkFile -- TrkFile for the reference tracker (current movie)
%   testTrkFile -- TrkFile for the test tracker (current movie)
%   nframes -- number of frames in the current movie
%   quantileThreshold -- in [0, 1]; higher keeps only the largest
%     per-frame distances
%   centroidMatchThreshold -- pixel distance above which two tracklets
%     are considered unrelated and the ref frame is dropped
%
% Returns empty column vectors and NaN threshold when there are no bouts.

% Sanity-check the inputs.
assert(isa(refTrkFile, 'TrkFile'), ...
       'refTrkFile must be a TrkFile') ;
assert(isa(testTrkFile, 'TrkFile'), ...
       'testTrkFile must be a TrkFile') ;
assert(isscalar(nframes) && isnumeric(nframes) && isreal(nframes) && ...
       isfinite(nframes) && nframes == round(nframes) && nframes >= 0, ...
       'nframes must be a nonnegative integer') ;
assert(isscalar(quantileThreshold) && isnumeric(quantileThreshold) && ...
       isreal(quantileThreshold) && isfinite(quantileThreshold) && ...
       0 <= quantileThreshold && quantileThreshold <= 1, ...
       'quantileThreshold must be a finite scalar in [0, 1]') ;
assert(isscalar(centroidMatchThreshold) && isnumeric(centroidMatchThreshold) && ...
       isreal(centroidMatchThreshold) && isfinite(centroidMatchThreshold) && ...
       centroidMatchThreshold >= 0, ...
       'centroidMatchThreshold must be a nonnegative finite scalar') ;

% Precompute per-test-tracklet (xy, centroid) data by frame.
testTrackletsAtFrame = buildTestTrackletsAtFrame_(testTrkFile, nframes) ;

% Gather per-frame max-distance data for each reference tracklet.
refTrackletCount = refTrkFile.ntracklets ;
refTrackletIndices = (1 : refTrackletCount)' ;
[frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
 trackletIndexFromTrackletIndex, ...
 targetIndexFromTrackletIndex, ...
 interestFromTrackletFrameIndexFromTrackletIndex] = ...
  arrayfun(@(refTrackletIndex) collectDistanceDataForSingleRefTracklet(refTrkFile, ...
                                                                       refTrackletIndex, ...
                                                                       testTrackletsAtFrame, ...
                                                                       centroidMatchThreshold), ...
                                                                       refTrackletIndices, ...
                                                                       'UniformOutput', false) ;

% Run the shared bout-formation / quantile / sort pipeline.  Distance is
% already an interest signal (higher = more interesting), so no
% sign-flipping at the boundary.
[firstFrameIndexFromSortedBoutIndex, ...
 lastFrameIndexFromSortedBoutIndex, ...
 maxDistanceFrameIndexFromSortedBoutIndex, ...
 trackletIndexFromSortedBoutIndex, ...
 targetIndexFromSortedBoutIndex, ...
 maxDistanceFromSortedBoutIndex, ...
 absoluteDistanceThreshold] = ...
  interestBoutsFromPerTrackletData(frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
                                   trackletIndexFromTrackletIndex, ...
                                   targetIndexFromTrackletIndex, ...
                                   interestFromTrackletFrameIndexFromTrackletIndex, ...
                                   quantileThreshold) ;

end  % function



function testTrackletsAtFrame = buildTestTrackletsAtFrame_(testTrkFile, nframes)
% Build a per-frame lookup of test tracklets that have data at that
% frame.  Each cell holds a struct array with fields trackletIndex,
% centroid (2x1), and xy (npt x 2).

emptyEntry = struct('trackletIndex', {}, 'centroid', {}, 'xy', {}) ;
testTrackletsAtFrame = repmat({emptyEntry}, nframes, 1) ;

if isempty(testTrkFile) || testTrkFile.ntracklets == 0
  return
end

testTrackletCount = testTrkFile.ntracklets ;
for testTrackletIndex = 1 : testTrackletCount
  [xyByLandmarkAndAxisAndFrame, ~, frameIndices] = ...
    testTrkFile.getPTrkTgt(testTrackletIndex) ;
  if isempty(frameIndices) || isempty(xyByLandmarkAndAxisAndFrame)
    continue
  end
  centroidByAxisAndFrame = ...
    squeeze(mean(xyByLandmarkAndAxisAndFrame, 1, 'omitnan')) ;  % [2 x nf] or [2 x 1]
  if size(xyByLandmarkAndAxisAndFrame, 3) == 1
    centroidByAxisAndFrame = centroidByAxisAndFrame(:) ;
  end
  for localFrameIndex = 1 : numel(frameIndices)
    movieFrame = frameIndices(localFrameIndex) ;
    if movieFrame < 1 || movieFrame > nframes
      continue
    end
    centroid = centroidByAxisAndFrame(:, localFrameIndex) ;
    if any(~isfinite(centroid))
      continue
    end
    entry = struct('trackletIndex', testTrackletIndex, ...
                   'centroid', centroid, ...
                   'xy', xyByLandmarkAndAxisAndFrame(:, :, localFrameIndex)) ;
    testTrackletsAtFrame{movieFrame}(end+1) = entry ;
  end
end

end  % function
