function [firstFrameIndexFromSortedBoutIndex, ...
          lastFrameIndexFromSortedBoutIndex, ...
          maxDistanceFrameIndexFromSortedBoutIndex, ...
          trackletIndexFromSortedBoutIndex, ...
          testTrackletIndexFromSortedBoutIndex, ...
          targetIndexFromSortedBoutIndex, ...
          maxDistanceFromSortedBoutIndex, ...
          absoluteDistanceThreshold] = ...
  distanceBoutsBetweenTrackers(refTrkFile, ...
                               testTrkFile, ...
                               nframes, ...
                               quantileThreshold, ...
                               matchDistanceThreshold)
% Find bouts of consecutive frames where the per-frame max landmark
% distance between a reference tracker's tracklet and its matched test
% tracker tracklet is at or above a quantile-derived threshold.
%
% At each frame, the ref poses and test poses present at that frame are
% put into one-to-one correspondence by Hungarian matching (matchpairs),
% as in computeMAErr().  The assignment cost for a (ref, test) pose pair
% is the mean over landmarks of the landmark-to-landmark distance, and
% pairs whose cost is matchDistanceThreshold or more are left unmatched.
% The per-frame interest signal is the max over landmarks of the
% ref-to-test landmark distance.  Ref frames with no matched test pose
% are dropped.  Bouts are returned sorted by per-bout max distance,
% descending (largest disagreement first).
%
% Inputs:
%   refTrkFile -- TrkFile for the reference tracker (current movie)
%   testTrkFile -- TrkFile for the test tracker (current movie)
%   nframes -- number of frames in the current movie
%   quantileThreshold -- in [0, 1]; higher keeps only the largest
%     per-frame distances
%   matchDistanceThreshold -- mean-over-landmarks pixel distance at or
%     above which a ref pose and a test pose are considered unrelated
%     and left unmatched
%
% testTrackletIndexFromSortedBoutIndex gives, for each bout, the index of
% the test-tracker tracklet (into the test TrkFile) that was
% Hungarian-matched to the bout's ref tracklet at the bout's max-distance
% frame.
%
% Returns empty column vectors and NaN threshold when there are no bouts.

% Sanity-check the inputs.
assert(isa(refTrkFile, 'TrkFile'), ...
       'refTrkFile must be a TrkFile') ;
assert(isa(testTrkFile, 'TrkFile'), ...
       'testTrkFile must be a TrkFile') ;
assert(isscalar(nframes) && isnumeric(nframes) && isreal(nframes) && ...
       isfinite(nframes) && nframes == round(nframes) && nframes >= 0, ...
       'nframes must be a nonnegative integer') ;
assert(isscalar(quantileThreshold) && isnumeric(quantileThreshold) && ...
       isreal(quantileThreshold) && isfinite(quantileThreshold) && ...
       0 <= quantileThreshold && quantileThreshold <= 1, ...
       'quantileThreshold must be a finite scalar in [0, 1]') ;
assert(isscalar(matchDistanceThreshold) && isnumeric(matchDistanceThreshold) && ...
       isreal(matchDistanceThreshold) && isfinite(matchDistanceThreshold) && ...
       matchDistanceThreshold >= 0, ...
       'matchDistanceThreshold must be a nonnegative finite scalar') ;

% At each frame, Hungarian-match the ref poses to the test poses, and
% record the max landmark distance for each matched ref pose.
refTrackletCount = refTrkFile.ntracklets ;
[distanceFromFrameIndexAndTrackletIndex, ...
 testTrackletIndexFromFrameIndexAndTrackletIndex] = ...
  perFrameTrackerMatch(refTrkFile, testTrkFile, nframes, matchDistanceThreshold) ;

% Repackage the matched distances as per-tracklet cell arrays for the
% shared bout-formation pipeline.
frameIndexFromTrackletFrameIndexFromTrackletIndex = cell(refTrackletCount, 1) ;
trackletIndexFromTrackletIndex = cell(refTrackletCount, 1) ;
targetIndexFromTrackletIndex = cell(refTrackletCount, 1) ;
interestFromTrackletFrameIndexFromTrackletIndex = cell(refTrackletCount, 1) ;
for trackletIndex = 1 : refTrackletCount
  isValidFromFrameIndex = isfinite(distanceFromFrameIndexAndTrackletIndex(:, trackletIndex)) ;
  frameIndexFromTrackletFrameIndexFromTrackletIndex{trackletIndex} = find(isValidFromFrameIndex) ;
  trackletIndexFromTrackletIndex{trackletIndex} = trackletIndex ;
  targetIndexFromTrackletIndex{trackletIndex} = refTrkFile.pTrkiTgt(trackletIndex) ;
  interestFromTrackletFrameIndexFromTrackletIndex{trackletIndex} = ...
    distanceFromFrameIndexAndTrackletIndex(isValidFromFrameIndex, trackletIndex) ;
end

% Run the shared bout-formation / quantile / sort pipeline.  The interest
% signal here is the per-frame max-over-landmarks distance (see above for
% why max rather than the mean used for matching); it is already oriented
% so that higher = more interesting, so no sign-flipping at the boundary.
[firstFrameIndexFromSortedBoutIndex, ...
 lastFrameIndexFromSortedBoutIndex, ...
 maxDistanceFrameIndexFromSortedBoutIndex, ...
 trackletIndexFromSortedBoutIndex, ...
 targetIndexFromSortedBoutIndex, ...
 maxDistanceFromSortedBoutIndex, ...
 absoluteDistanceThreshold] = ...
  interestBoutsFromPerTrackletData(frameIndexFromTrackletFrameIndexFromTrackletIndex, ...
                                   trackletIndexFromTrackletIndex, ...
                                   targetIndexFromTrackletIndex, ...
                                   interestFromTrackletFrameIndexFromTrackletIndex, ...
                                   quantileThreshold) ;

% Look up, for each bout, the test tracklet that was matched to the ref
% tracklet at the bout's max-distance frame.
boutCount = numel(maxDistanceFrameIndexFromSortedBoutIndex) ;
testTrackletIndexFromSortedBoutIndex = nan(boutCount, 1) ;
for boutIndex = 1 : boutCount
  maxDistanceFrameIndex = maxDistanceFrameIndexFromSortedBoutIndex(boutIndex) ;
  refTrackletIndex = trackletIndexFromSortedBoutIndex(boutIndex) ;
  testTrackletIndexFromSortedBoutIndex(boutIndex) = ...
    testTrackletIndexFromFrameIndexAndTrackletIndex(maxDistanceFrameIndex, refTrackletIndex) ;
end

end  % function
