function cmd = generateLogCommandForDockerBackend(backend, containerName, native_log_file_name)

assert(backend.type == DLBackEnd.Docker);
dockercmd = apt.dockercmd();
log_file_name = linux_path(native_log_file_name) ;
cmd = ...
  sprintf('%s logs -f %s &> %s', ... 
          dockercmd, ...
          containerName, ...
          escape_string_for_bash(log_file_name)) ;
cmd = [cmd,' &'];
