function result = is_a_numeric_class_name(class_name)
    result = ...
        isequal(class_name,'double') || ...            
        isequal(class_name,'single') || ...
        isequal(class_name,'int8') || ...
        isequal(class_name,'uint8') || ...
        isequal(class_name,'int16') || ...
        isequal(class_name,'uint16') || ...
        isequal(class_name,'int32') || ...
        isequal(class_name,'uint32') || ...
        isequal(class_name,'int64') || ...
        isequal(class_name,'uint64') ;
end
