function result = is_index_in_range(index, count)
% Reuturns true iff index is a valid scalar index into an array with count
% elements.

result = isnumeric(index) && ...
         isscalar(index) && ...
         round(index)==index && ...
         1<=index && ...
         index<=count ;

