function codestr = trackCodeGenSSHBsubSing(backend, fileinfo,frm0,frm1,varargin)

[baseargs,singargs,bsubargs,sshargs] = myparse(varargin,...
  'baseargs',{},...
  'singargs',{},...
  'bsubargs',{},...
  'sshargs',{}...
  );
baseargs = [baseargs {'cache' fileinfo.cache}];      
      
remotecmd = backend.trackCodeGenBsubSing(fileinfo,frm0,frm1,...
                                     'baseargs',baseargs,'singargs',singargs,'bsubargs',bsubargs);
codestr = DeepTracker.codeGenSSHGeneral(remotecmd,sshargs{:});

end
