function [firstFrameIndexFromSortedBoutIndex, ...
          lastFrameIndexFromSortedBoutIndex, ...
          maxCountFrameIndexFromSortedBoutIndex, ...
          maxCountFromSortedBoutIndex, ...
          absoluteCountThreshold, ...
          isUnmatchedRefFromFrameIndexAndTrackletIndex, ...
          isMatchedRefFromFrameIndexAndTrackletIndex] = ...
  unmatchedCountBoutsBetweenTrackers(refTrkFile, ...
                                     testTrkFile, ...
                                     nframes, ...
                                     quantileThreshold, ...
                                     matchDistanceThreshold)
% Find bouts of consecutive frames where the number of reference tracker
% tracklets left unmatched by the test tracker is at or above a
% quantile-derived threshold.
%
% At each frame, the ref poses and test poses present are put into
% one-to-one correspondence by Hungarian matching (see perFrameTrackerMatch),
% and the per-frame interest signal is the number of ref poses the matcher
% left without a test partner.  The interest distribution is taken over
% the frames that have at least one ref pose present (frames with all-
% matched animals contribute a zero; frames with no ref pose at all are
% excluded, mirroring distanceBoutsBetweenTrackers).  Bouts are contiguous
% runs of those in-domain frames whose unmatched count is at or above the
% threshold, returned sorted by per-bout max count, descending.
%
% Inputs:
%   refTrkFile -- TrkFile for the reference tracker (current movie)
%   testTrkFile -- TrkFile for the test tracker (current movie)
%   nframes -- number of frames in the current movie
%   quantileThreshold -- in [0, 1]; higher keeps only the largest
%     per-frame unmatched counts
%   matchDistanceThreshold -- mean-over-landmarks pixel distance at or
%     above which a ref pose and a test pose are considered unrelated and
%     left unmatched
%
% Returns empty column vectors and NaN threshold when there are no bouts.

% Sanity-check the inputs.
assert(isa(refTrkFile, 'TrkFile'), ...
       'refTrkFile must be a TrkFile') ;
assert(isa(testTrkFile, 'TrkFile'), ...
       'testTrkFile must be a TrkFile') ;
assert(isscalar(nframes) && isnumeric(nframes) && isreal(nframes) && ...
       isfinite(nframes) && nframes == round(nframes) && nframes >= 0, ...
       'nframes must be a nonnegative integer') ;
assert(isscalar(quantileThreshold) && isnumeric(quantileThreshold) && ...
       isreal(quantileThreshold) && isfinite(quantileThreshold) && ...
       0 <= quantileThreshold && quantileThreshold <= 1, ...
       'quantileThreshold must be a finite scalar in [0, 1]') ;
assert(isscalar(matchDistanceThreshold) && isnumeric(matchDistanceThreshold) && ...
       isreal(matchDistanceThreshold) && isfinite(matchDistanceThreshold) && ...
       matchDistanceThreshold >= 0, ...
       'matchDistanceThreshold must be a nonnegative finite scalar') ;

% At each frame, Hungarian-match the ref poses to the test poses, and
% count how many ref poses were left unmatched.  The per-tracklet unmatched
% and matched masks are returned so the caller can mark the animals'
% centroids.
[~, ...
 ~, ...
 refPoseCountFromFrameIndex, ...
 unmatchedRefCountFromFrameIndex, ...
 isUnmatchedRefFromFrameIndexAndTrackletIndex, ...
 isMatchedRefFromFrameIndexAndTrackletIndex] = ...
  perFrameTrackerMatch(refTrkFile, testTrkFile, nframes, matchDistanceThreshold) ;

% The interest signal is per-frame (not per-tracklet), so feed the shared
% bout pipeline a single synthetic "tracklet" spanning the in-domain
% frames -- those with at least one ref pose present.  The tracklet and
% target indices are unused for this mode, so pass NaN.
isInDomainFromFrameIndex = (refPoseCountFromFrameIndex >= 1) ;
inDomainFrameIndices = find(isInDomainFromFrameIndex) ;
unmatchedCountFromInDomainFrameIndex = unmatchedRefCountFromFrameIndex(isInDomainFromFrameIndex) ;

[firstFrameIndexFromSortedBoutIndex, ...
 lastFrameIndexFromSortedBoutIndex, ...
 maxCountFrameIndexFromSortedBoutIndex, ...
 ~, ...
 ~, ...
 maxCountFromSortedBoutIndex, ...
 absoluteCountThreshold] = ...
  interestBoutsFromPerTrackletData({inDomainFrameIndices}, ...
                                   {nan}, ...
                                   {nan}, ...
                                   {unmatchedCountFromInDomainFrameIndex}, ...
                                   quantileThreshold) ;

end  % function
