function codestr = wrapBaseCommandForDockerBackendGT(basecmd, varargin)
% Take a base command and run it in a docker img, for GT.  
% Created this b/c didn't want to break GT stuff when I was messing with
% DLBackEndClass functionality for regular tracking/training.  Should probably
% be folded into the DLBackEndClass code, or eliminated somehow.  
%   -- ALT, 2024-09-17

% Parse keyword args
[containerName,bindpath,isgpu,gpuid,tfDetach,tty,shmSize,dockerimg,dockerapiver,dockerremotehost] = ...
  myparse(varargin,...
          'containername','aptainer',...
          'bindpath',{},... % paths on local filesystem that must be mounted/bound within container
          'isgpu',true,... % set to false for CPU-only
          'gpuid',0,... % used if isgpu
          'detach',true, ...
          'tty',false,...
          'shmsize',[], ... optional
          'dockerimg',[], ...
          'dockerapiver','1.40', ...
          'dockerremotehost','' ...
          );

% Call main function, returns Linux/WSL-style command string
codestr = ...
  wrapCommandDocker(basecmd, ...
                    'containername',containerName,...
                    'bindpath',bindpath,...
                    'dockerimg',dockerimg,...
                    'isgpu',isgpu,...
                    'gpuid',gpuid,...
                    'detach',tfDetach, ...
                    'tty',tty,...
                    'shmsize',shmSize, ...
                    'apiver',dockerapiver) ;

% Wrap for ssh'ing into a remote docker host, if needed
if ~isempty(dockerremotehost),
  codestr = wrapCommandSSH(codestr,'host',dockerremotehost);
end

% Wrap command for running in WSL, if needed
codestr = wrap_linux_command_line_for_wsl_if_needed(codestr) ;
