function hh = basicImageDisplay(fig_handle,ax_handle,...
                                cdata, cdatamapping, clim, map, ...
                                xdata, ydata)
%basicImageDisplay Display image for IMSHOW and IMVIEW.

%   Copyright 1993-2004 The MathWorks, Inc.  
%   $Revision: 1.1.8.2 $  $Date: 2005/03/31 16:33:17 $
  
hh = image(xdata,ydata,cdata, ...
           'BusyAction', 'cancel', ...
           'Parent', ax_handle, ...
           'CDataMapping', cdatamapping, ...
           'Interruptible', 'off');

% Set axes and figure properties if necessary to display the 
% image object correctly.
show_axes = iptgetpref('ImshowAxesVisible');
set(ax_handle, ...
    'YDir','reverse',...
    'TickDir', 'out', ...
    'XGrid', 'off', ...
    'YGrid', 'off', ...
    'DataAspectRatio', [1 1 1], ...
    'PlotBoxAspectRatioMode', 'auto', ...
    'Visible', show_axes);

if (~isempty(map))
    set(fig_handle, 'Colormap', map);
end

if (~isempty(clim))
    set(ax_handle, 'CLim', clim);
end

isIndexedUint16Image = strcmpi(get(hh,'CDataMapping'),'direct') && size(map,1) > 256;

% This is to workaround the problem of indexed image showing up black on
% windows.  G208494
if isIndexedUint16Image && ispc
  set(fig_handle,'Renderer','Zbuffer');
end
