function q = iscpstruct(t)
%ISCPSTRUCT True for control point structure.
%   Q = ISCPSTRUCT(T) returns true if and only if T is a structure array
%   with the standard CPSTRUCT fields produced by CPSELECT.
% 
%   See also CPSELECT, CP2TFORM, CPSTRUCT2PAIRS.

%   Copyright 2005 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $ $Date: 2005/05/27 14:07:24 $

q = isa(t,'struct') ...
    & isfield(t,'inputPoints') ...
    & isfield(t,'basePoints') ...
    & isfield(t,'inputBasePairs') ...
    & isfield(t,'ids') ...
    & isfield(t,'inputIdPairs') ...
    & isfield(t,'baseIdPairs') ...
    & isfield(t,'isInputPredicted') ...
    & isfield(t,'isBasePredicted');
