function [slocgrp] = genLocsGroupedI(s,imov,varargin)
  % s: scalar element of 'sagg', ie labels data structure for one movie.
  % imov: movie index, only used for metadata

  imgpat = myparse(varargin,...
    'imgpat','im/%s.png' ...
    );

%       s = Labels.addsplitsifnec(s);

  slocgrp = [];
  frmsun = unique([s.frm(:); s.frmroi(:)]);
  nfrmsun = numel(frmsun);
  for ifrmun=1:nfrmsun
    f = frmsun(ifrmun);
    j = find(s.frm==f);
    ntgt = numel(j);

    jroi = find(s.frmroi==f);
    nroi = numel(jroi);

    % Dont include numtgts, eg what if a target is added to an
    % existing frame.
    basefS = sprintf('mov%04d_frm%08d',imov,f);
    img = sprintf(imgpat,basefS);
    sloctmp = struct(...
      'id',basefS,...
      'idmovfrm',sprintf('mov%04d_frm%08d',imov,f),...
      'img',{{img}},...
      'imov',imov,...
      'mov',s.mov,...
      'frm',f,...
      'ntgt',ntgt,...
      'split',s.split(j),...
      'itgt',s.tgt(j),...
      'roi',s.roi(:,j),...
      'pabs',s.p(:,j), ...
      'occ',s.occ(:,j), ...
      'ts',s.ts(:,j), ...
      'nextra_roi',nroi,...
      'extra_roi',reshape(s.extra_roi(:,:,jroi),[],nroi) ...
      );
    slocgrp = [slocgrp; sloctmp]; %#ok<AGROW>
  end
end % function
